# Generated by: Agent 99998
#!/usr/bin/env python3
"""
1d_WeeklyPivot_Bias_With_Trend
Hypothesis: Weekly pivot bias (price relative to weekly pivot point) combined with 1-week trend filter and volume confirmation.
In bull markets: price above weekly pivot + uptrend = long bias.
In bear markets: price below weekly pivot + downtrend = short bias.
Volume spike confirms institutional participation. Designed for low trade frequency (~15-25/year) to minimize fee drag.
Works on BTC/ETH by capturing institutional bias around key weekly levels.
"""

import numpy as np
import pandas as pd
from mtf_data import get_htf_data, align_htf_to_ltf

def generate_signals(prices):
    n = len(prices)
    if n < 50:
        return np.zeros(n)
    
    close = prices['close'].values
    high = prices['high'].values
    low = prices['low'].values
    volume = prices['volume'].values
    
    # Get weekly data for pivot calculation and trend filter
    df_1w = get_htf_data(prices, '1w')
    if len(df_1w) < 2:  # Need at least 2 weeks for pivot calculation
        return np.zeros(n)
    
    # Weekly high, low, close from previous week (to avoid look-ahead)
    weekly_high = df_1w['high'].values
    weekly_low = df_1w['low'].values
    weekly_close = df_1w['close'].values
    
    # Calculate weekly pivot point and support/resistance levels
    # Standard pivot: P = (H + L + C) / 3
    weekly_pivot = (weekly_high + weekly_low + weekly_close) / 3.0
    # Support 1: S1 = 2*P - H
    weekly_s1 = 2 * weekly_pivot - weekly_high
    # Resistance 1: R1 = 2*P - L
    weekly_r1 = 2 * weekly_pivot - weekly_low
    
    # Align weekly levels to daily timeframe (previous week's levels available at open)
    pivot_aligned = align_htf_to_ltf(prices, df_1w, weekly_pivot)
    s1_aligned = align_htf_to_ltf(prices, df_1w, weekly_s1)
    r1_aligned = align_htf_to_ltf(prices, df_1w, weekly_r1)
    
    # Weekly trend filter: EMA21 on weekly close
    weekly_ema21 = pd.Series(weekly_close).ewm(span=21, adjust=False, min_periods=21).mean().values
    ema21_aligned = align_htf_to_ltf(prices, df_1w, weekly_ema21)
    
    # Volume spike detection (20-period average on daily)
    vol_ma = pd.Series(volume).rolling(window=20, min_periods=20).mean().values
    volume_spike = volume > (vol_ma * 1.5)  # 1.5x average volume
    
    signals = np.zeros(n)
    position = 0  # 0: flat, 1: long, -1: short
    
    # Warmup period - need enough for weekly calculations and volume MA
    start_idx = 20
    
    for i in range(start_idx, n):
        # Skip if any required data is NaN
        if (np.isnan(pivot_aligned[i]) or np.isnan(s1_aligned[i]) or 
            np.isnan(r1_aligned[i]) or np.isnan(ema21_aligned[i]) or 
            np.isnan(vol_ma[i])):
            signals[i] = 0.0
            continue
        
        if position == 0:
            # Long: price above weekly pivot AND above weekly S1, with weekly uptrend and volume spike
            if (close[i] > pivot_aligned[i] and close[i] > s1_aligned[i] and
                close[i] > ema21_aligned[i] and volume_spike[i]):
                signals[i] = 0.25
                position = 1
            # Short: price below weekly pivot AND below weekly R1, with weekly downtrend and volume spike
            elif (close[i] < pivot_aligned[i] and close[i] < r1_aligned[i] and
                  close[i] < ema21_aligned[i] and volume_spike[i]):
                signals[i] = -0.25
                position = -1
            else:
                signals[i] = 0.0
        elif position == 1:
            # Long exit: price crosses below weekly pivot OR weekly trend turns down
            if (close[i] < pivot_aligned[i] or 
                close[i] < ema21_aligned[i]):
                signals[i] = 0.0
                position = 0
            else:
                signals[i] = 0.25
        elif position == -1:
            # Short exit: price crosses above weekly pivot OR weekly trend turns up
            if (close[i] > pivot_aligned[i] or 
                close[i] > ema21_aligned[i]):
                signals[i] = 0.0
                position = 0
            else:
                signals[i] = -0.25
    
    return signals

name = "1d_WeeklyPivot_Bias_With_Trend"
timeframe = "1d"
leverage = 1.0