# Generated by: Agentic Agent
# Strategy: 4h_Camarilla_Pivot_VolumeSpike_TrendFilter
# Hypothesis: Camarilla pivot levels (R1/S1) from 1d timeframe act as strong support/resistance. Breakouts above R1 or below S1 with volume spike (>1.5x 20-period average) and aligned 1d trend (close > EMA50) capture momentum moves. Works in bull/bear by taking breakouts only in direction of higher timeframe trend. Targets 20-40 trades/year to minimize fee drag.

import numpy as np
import pandas as pd
from mtf_data import get_htf_data, align_htf_to_ltf

def calculate_ema(close, span):
    """Calculate Exponential Moving Average"""
    return pd.Series(close).ewm(span=span, adjust=False).mean().values

def generate_signals(prices):
    n = len(prices)
    if n < 50:
        return np.zeros(n)
    
    # Load 1d data once for Camarilla pivots and trend filter
    df_1d = get_htf_data(prices, '1d')
    if len(df_1d) < 50:
        return np.zeros(n)
    
    # Calculate 1d EMA50 for trend filter
    close_1d = df_1d['close'].values
    ema_50_1d = calculate_ema(close_1d, 50)
    ema_50_1d_aligned = align_htf_to_ltf(prices, df_1d, ema_50_1d)
    
    # Calculate Camarilla pivot levels (R1, S1) from prior 1d candle
    high_1d = df_1d['high'].values
    low_1d = df_1d['low'].values
    close_1d = df_1d['close'].values
    
    # Typical price for pivot calculation
    typical_price = (high_1d + low_1d + close_1d) / 3
    range_1d = high_1d - low_1d
    
    # Camarilla levels
    R1 = close_1d + (range_1d * 1.1 / 12)
    S1 = close_1d - (range_1d * 1.1 / 12)
    
    # Align pivot levels to 4h timeframe (use prior day's levels)
    R1_aligned = align_htf_to_ltf(prices, df_1d, R1)
    S1_aligned = align_htf_to_ltf(prices, df_1d, S1)
    
    signals = np.zeros(n)
    position = 0  # 0: flat, 1: long, -1: short
    
    for i in range(20, n):
        # Skip if indicators not ready
        if np.isnan(ema_50_1d_aligned[i]) or np.isnan(R1_aligned[i]) or np.isnan(S1_aligned[i]):
            if position != 0:
                signals[i] = 0.0
                position = 0
            continue
        
        price = prices['close'].iloc[i]
        volume = prices['volume'].iloc[i]
        
        # Volume filter: current volume > 1.5 * 20-period average
        if i >= 20:
            vol_ma = prices['volume'].iloc[i-20:i].mean()
            volume_ok = volume > 1.5 * vol_ma
        else:
            volume_ok = False
        
        if position == 0:
            # Long breakout: price > R1 AND volume spike AND uptrend (price > EMA50)
            if price > R1_aligned[i] and volume_ok and price > ema_50_1d_aligned[i]:
                signals[i] = 0.25
                position = 1
            # Short breakdown: price < S1 AND volume spike AND downtrend (price < EMA50)
            elif price < S1_aligned[i] and volume_ok and price < ema_50_1d_aligned[i]:
                signals[i] = -0.25
                position = -1
        
        elif position == 1:
            # Long exit: price < S1 (reversal) OR trend change (price < EMA50)
            if price < S1_aligned[i] or price < ema_50_1d_aligned[i]:
                signals[i] = 0.0
                position = 0
            else:
                signals[i] = 0.25
        
        elif position == -1:
            # Short exit: price > R1 (reversal) OR trend change (price > EMA50)
            if price > R1_aligned[i] or price > ema_50_1d_aligned[i]:
                signals[i] = 0.0
                position = 0
            else:
                signals[i] = -0.25
    
    return signals

name = "4h_Camarilla_Pivot_VolumeSpike_TrendFilter"
timeframe = "4h"
leverage = 1.0