//@version=4
strategy("Moving Average Crossover 1", overlay= true)


ema5 = ema(close, 5)
ema20 = ema(close, 20)

long = ema5 > ema20
short = ema5 < ema20



colorBasis = ema5 >= ema20 ? color.green : color.red

pBasis = plot(ema20, linewidth=4, color=colorBasis)

strategy.entry("long", strategy.long, 1000.0, when=long)


strategy.close("long", when = short)
View in Pine Editor・26 lines
Use on chart
8
2
2 471
This indicator is based on ema 5 and ema 20, when ema 5 crosses over ema 20, the line will be green, when ema 5 crosses down it will be red

This indicator has been accompanied by a strategy so we can see the results through the strategy tester, this strategy there is only a long, I recommend using a weekly timeframe because the volatility is lower and minimal with false signals
