//@version=4
strategy(title="Buy and hold calculator", overlay=true, initial_capital = 1, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent  )



fromDay = input(defval = 1, title = "From Day", minval = 1, maxval = 31)
fromMonth = input(defval = 1, title = "From Month", minval = 1, maxval = 12)
fromYear = input(defval = 2000, title = "From Year", minval = 1970)
 //monday and session 
// To Date Inputs
toDay = input(defval = 31, title = "To Day", minval = 1, maxval = 31)
toMonth = input(defval = 12, title = "To Month", minval = 1, maxval = 12)
toYear = input(defval = 2020, title = "To Year", minval = 1970)

startDate = timestamp(fromYear, fromMonth, fromDay, 00, 00)
finishDate = timestamp(toYear, toMonth, toDay, 00, 00)
time_cond = time >= startDate and time <= finishDate 

strategy.entry("long",1,when=time_cond)
strategy.close("long",when= not time_cond)

View in Pine Editor・23 lines
Use on chart
1
6
7
3
5 652
This is a simple buy and hold calculator.

You have an initial date and once that dated it passed it will sell the product that was bought initially.

This strategy buys and sell 100% of the initial volume.
