//@version=4
strategy("Stock_Strat_HL_V1", overlay=true)

Week = security(syminfo.tickerid,'D',open)

H = highest(Week[1],16)
L = lowest(Week[1],16)

plot(H)
plot(L)

longCondition = close > H and H[2] > H[1]
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long,stop=H)
    strategy.exit("My Long Entry Id",profit=1000,loss=100,trail_points=100)

shortCondition = close < L and L[2] > L[1]
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short,stop=L)
    strategy.exit("My Short Entry Id",profit=1000,loss=100,trail_points=100)

View in Pine Editor・20 lines
Use on chart
1
4
2
1
1 972
Stock_Strat_HL_V1
