//@version=4
strategy("Estamina Trend Strategy By KrisWaters",overlay=true,precision=8,pyramiding=0,default_qty_type=strategy.percent_of_equity,default_qty_value=100,currency='USD',commission_type= strategy.commission.percent,commission_value=0.075,initial_capital=1000) 

fastMaPeriod = input(4,title="fastMaPeriod")
smoothedMaPeriod = input(8,title="smoothedMaPeriod")
slowMaPeriod = input(15,title="slowMaPeriod")

fastMaValue = sma(close,fastMaPeriod)
smoothedMaValue = 0.0
smoothedMaValue := na(smoothedMaValue[1]) ? sma(close, smoothedMaPeriod) : (smoothedMaValue[1] * (smoothedMaPeriod - 1) + close) / smoothedMaPeriod
slowMaValue = sma(close,slowMaPeriod)

plot(fastMaValue,title="Fast MA Value",color=color.purple,linewidth=3)
plot(smoothedMaValue,title="Smoothed MA Value",color=color.orange,linewidth=3)
plot(slowMaValue,title="Slow MA Value",color=color.green,linewidth=3)

if fastMaValue > smoothedMaValue and fastMaValue > slowMaValue
    strategy.entry("long",strategy.long)

if crossunder(fastMaValue,smoothedMaValue) or crossunder(fastMaValue,slowMaValue)
    strategy.close("long")

View in Pine Editor・24 lines
Use on chart
1
2
2
1
3 166
Trend following strategy based on moving avarage crossovers. Strategy provides only long signals. Use only for BTCUSDT pair on 4H timeframe.
