//@version=5
strategy("Sell in May, buy in September Strategy", overlay=false)

longCondition = month==9
closecondition = month==5

if longCondition
    strategy.entry("long", strategy.long)

if closecondition
    strategy.close("long", when=closecondition)

View in Pine Editor・14 lines
Use on chart
9
2
4
4 556
Dear TV'ers,

This script applies the classic traders mantra of "Sell in May, buy in September". Not much else to it to be honest. Seems to work though :-).
