//@version=5
//@fenyesk
strategy("Timeshifter Triple Timeframe Strategy w/ Sessions", overlay=true, margin_long=100, margin_short=100)

// Inputs for timeframes
higherTimeframe = input.timeframe("D", "Higher Timeframe")
lowerTimeframe = input.timeframe("M15", "Lower Timeframe")

// Set medium timeframe to the current chart timeframe
mediumTimeframe = timeframe.period

// Inputs for optimization using input.int
higherTfMALength = input.int(50, "Higher TF MA Length", minval=10, maxval=200)
mediumTfMALength = input.int(20, "Medium TF MA Length", minval=5, maxval=100)
lowerTfMALength = input.int(10, "Lower TF MA Length", minval=2, maxval=50)

// Dropdown for selecting indicators
selectedIndicator = input.string("RMI", "Select Indicator", options=["RMI", "TWAP", "TEMA", "DEMA", "MA", "MFI", "VWMA", "PSAR"])

// Checkbox for ADX confirmation
useADX = input.bool(false, "Use ADX Confirmation")

// Inputs for trade direction
tradeDirection = input.string("Both", "Trade Direction", options=["Long", "Short", "Both"])

// Inputs for ADX
adxLength = input(14, "ADX Length")
adxThreshold = input(25, "ADX Threshold")

// Inputs for RMI
rmiLength = input(14, "RMI Length")
rmiOverbought = input(70, "RMI Overbought Level")
rmiOversold = input(30, "RMI Oversold Level")

// Inputs for MA
maLength = input(20, "MA Length")

// Inputs for MFI
mfiLength = input(14, "MFI Length")
mfiOverbought = input(80, "MFI Overbought Level")
mfiOversold = input(20, "MFI Oversold Level")

// Inputs for VWMA
vwmaLength = input(20, "VWMA Length")

// Inputs for PSAR
psarStart = input(0.02, "PSAR Start")
psarIncrement = input(0.02, "PSAR Increment")
psarMaximum = input(0.2, "PSAR Maximum")

// Checkboxes for selecting trading sessions
useLondonSession = input.bool(true, "London Session")
useNewYorkSession = input.bool(true, "New York Session")
useTokyoSession = input.bool(true, "Tokyo Session")

// Define session times
isLondonSession = not na(time(timeframe.period, "0800-1700", "GMT+1"))
isNewYorkSession = not na(time(timeframe.period, "0800-1700", "GMT-5"))
isTokyoSession = not na(time(timeframe.period, "0900-1800", "GMT+9"))

// Fetch data from different timeframes
higherTFClose = request.security(syminfo.tickerid, higherTimeframe, close)
mediumTFClose = request.security(syminfo.tickerid, mediumTimeframe, close)
lowerTFClose = request.security(syminfo.tickerid, lowerTimeframe, close)

// Calculate moving averages for each timeframe
higherTFMA = ta.sma(higherTFClose, higherTfMALength)
mediumTFMA = ta.sma(mediumTFClose, mediumTfMALength)
lowerTFMA = ta.sma(lowerTFClose, lowerTfMALength)

// Calculate RMI
rmi(Length) =>
    up = ta.rma(math.max(close - close[1], 0), Length)
    down = ta.rma(math.max(close[1] - close, 0), Length)
    rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
    mfi = ta.mfi(close, Length)
    (rsi + mfi) / 2

currentRMI = rmi(rmiLength)

// TWAP Calculation
twapLength = input(20, "TWAP Length")
twap = ta.sma(hlc3, twapLength)

// TEMA Calculation
temaLength = input(20, "TEMA Length")
ema1 = ta.ema(close, temaLength)
ema2 = ta.ema(ema1, temaLength)
tema = ta.ema(ema2, temaLength)

// DEMA Calculation
demaLength = input(20, "DEMA Length")
ema1Dema = ta.ema(close, demaLength)
dema = 2 * ema1Dema - ta.ema(ema1Dema, demaLength)

// MA Calculation
ma = ta.sma(close, maLength)

// MFI Calculation
currentMFI = ta.mfi(close, mfiLength)

// VWMA Calculation
vwma = ta.vwma(close, vwmaLength)

// PSAR Calculation
psar = ta.sar(psarStart, psarIncrement, psarMaximum)

// ADX Calculation
[diPlus, diMinus, adx] = ta.dmi(adxLength, adxLength)

// Determine trend based on higher timeframe
higherTimeframeUptrend = higherTFClose > higherTFMA
higherTimeframeDowntrend = higherTFClose < higherTFMA

// Entry conditions based on medium timeframe
mediumTimeframeEntryLong = ta.crossover(mediumTFClose, mediumTFMA)
mediumTimeframeEntryShort = ta.crossunder(mediumTFClose, mediumTFMA)

// Exit conditions based on lower timeframe
lowerTimeframeExitLong = ta.crossunder(lowerTFClose, lowerTFMA)
lowerTimeframeExitShort = ta.crossover(lowerTFClose, lowerTFMA)

// Check if current time is within selected sessions
inSelectedSession = (useLondonSession and isLondonSession) or (useNewYorkSession and isNewYorkSession) or (useTokyoSession and isTokyoSession)

// Strategy logic
if inSelectedSession
    if tradeDirection == "Long" or tradeDirection == "Both"
        if higherTimeframeUptrend
            if mediumTimeframeEntryLong
                var bool entryCondition = false
                if selectedIndicator == "RMI"
                    entryCondition := currentRMI > rmiOverbought
                if selectedIndicator == "TWAP"
                    entryCondition := close > twap
                if selectedIndicator == "TEMA"
                    entryCondition := close > tema
                if selectedIndicator == "DEMA"
                    entryCondition := close > dema
                if selectedIndicator == "MA"
                    entryCondition := close > ma
                if selectedIndicator == "MFI"
                    entryCondition := currentMFI > mfiOverbought
                if selectedIndicator == "VWMA"
                    entryCondition := close > vwma
                if selectedIndicator == "PSAR"
                    entryCondition := close > psar

                adxCondition = useADX ? adx > adxThreshold : true

                if entryCondition and adxCondition
                    strategy.entry("Long", strategy.long)

        if lowerTimeframeExitLong
            strategy.close("Long")

    if tradeDirection == "Short" or tradeDirection == "Both"
        if higherTimeframeDowntrend
            if mediumTimeframeEntryShort
                var bool entryCondition = false
                if selectedIndicator == "RMI"
                    entryCondition := currentRMI < rmiOversold
                if selectedIndicator == "TWAP"
                    entryCondition := close < twap
                if selectedIndicator == "TEMA"
                    entryCondition := close < tema
                if selectedIndicator == "DEMA"
                    entryCondition := close < dema
                if selectedIndicator == "MA"
                    entryCondition := close < ma
                if selectedIndicator == "MFI"
                    entryCondition := currentMFI < mfiOversold
                if selectedIndicator == "VWMA"
                    entryCondition := close < vwma
                if selectedIndicator == "PSAR"
                    entryCondition := close < psar

                adxCondition = useADX ? adx > adxThreshold : true

                if entryCondition and adxCondition
                    strategy.entry("Short", strategy.short)

        if lowerTimeframeExitShort
            strategy.close("Short")

// Create a floating bubble with current settings and basic trading statistics
sessionsText = (useLondonSession ? "London, " : "") + (useNewYorkSession ? "New York, " : "") + (useTokyoSession ? "Tokyo" : "")

// Create a floating bubble with current settings and basic trading statistics
var bubbleText = "Current Settings:\nIndicator: " + selectedIndicator + "\nTrade Direction: " + tradeDirection + "\nUse ADX: " + str.tostring(useADX) + "\nSessions: " + sessionsText + "\n\nTrading Statistics:\nNet Profit: " + str.tostring(strategy.netprofit) + "\nGross Profit: " + str.tostring(strategy.grossprofit) + "\nGross Loss: " + str.tostring(strategy.grossloss)

// Display the bubble on the chart
var label statsBubble = na
if barstate.islast
    statsBubble := label.new(bar_index, high, text=bubbleText, style=label.style_label_left, color=color.new(color.blue, 90), textcolor=color.white)

View in Pine Editor・195 lines
Use on chart
5
9
2 274
Overview
The "Enhanced Timeshifter Triple Timeframe Strategy with Session Filtering" is a sophisticated trading strategy designed for the TradingView platform. It integrates multiple technical indicators across three different timeframes and allows traders to customize their trading Sessions. This strategy is ideal for traders who wish to leverage multi-timeframe analysis and session-based trading to enhance their trading decisions.

Features

Multi-Timeframe Analysis and direction:

Higher Timeframe: Set to a daily timeframe by default, providing a broader view of market trends.
Trading Timeframe: Automatically set to the current chart timeframe, ensuring alignment with the trader's primary analysis period.
Lower Timeframe: Set to a 15-minute timeframe by default, offering a granular view for precise entry and exit points.

Indicator Selection:

RMI (Relative Momentum Index): Combines RSI and MFI to gauge market momentum.

TWAP (Time Weighted Average Price): Provides an average price over a specified period, useful for identifying trends.

TEMA (Triple Exponential Moving Average): Reduces lag and smooths price data for trend identification.

DEMA (Double Exponential Moving Average): Similar to TEMA, it reduces lag and provides a smoother trend line.

MA (Moving Average): A simple moving average for basic trend analysis.

MFI (Money Flow Index): Measures the flow of money into and out of a security, useful for identifying overbought or oversold conditions.

VWMA (Volume Weighted Moving Average): Incorporates volume data into the moving average calculation.

PSAR (Parabolic SAR): Identifies potential reversals in price movement.

Session Filtering:

London Session: Trade during the London market hours (0800-1700 GMT+1).
New York Session: Trade during the New York market hours (0800-1700 GMT-5).
Tokyo Session: Trade during the Tokyo market hours (0900-1800 GMT+9).
Users can select one or multiple sessions to align trading with specific market hours.

Trade Direction:

Long: Only long trades are permitted.
Short: Only short trades are permitted.
Both: Both long and short trades are permitted, providing flexibility based on market conditions.
ADX Confirmation:

ADX (Average Directional Index): An optional filter to confirm the strength of a trend before entering a trade.

How to Use the Script

Setup:

Add the script to your TradingView chart.
Customize the input parameters according to your trading preferences and strategy requirements.

Indicator Selection:

Choose the primary indicator you wish to use for generating trading signals from the dropdown menu.
Enable or disable the ADX confirmation based on your preference for trend strength analysis.
Session Filtering:

Select the trading sessions you wish to trade in. You can choose one or multiple Sessions based on your trading strategy and market focus.
Trade Direction:

Set your preferred trade direction (Long, Short, or Both) to align with your market outlook and risk tolerance. You can use this feature to gauge the market and understand the possible directions.

Tips for Profitable and Safe Trading:

Recommended Timeframes Combination:

LT: 1m , CT: 5m, HT: 1H
LT: 1-5m , CT: 15m, HT: 4H
LT: 5-15m , CT: 4H, HT: 1W

Backtesting:

Always backtest the strategy on historical data to understand its performance under various market conditions.
Adjust the parameters based on backtesting results to optimize the strategy for your specific trading style.

Risk Management:

Use appropriate risk management techniques, such as setting stop-loss and take-profit levels, to protect your capital.
Avoid over-leveraging and ensure that you are trading within your risk tolerance.
Market Analysis:

Combine the script with other forms of market analysis, such as fundamental analysis or market sentiment, to make well-rounded trading decisions.
Stay informed about major economic events and news that could impact market volatility and trading sessions.

Continuous Monitoring:

Regularly monitor the strategy's performance and make adjustments as necessary.
Keep an eye on the results and settings for real-time statistics and ensure that the strategy aligns with current market conditions.

Education and Practice:

Continuously educate yourself on trading strategies and market dynamics.
Practice using the strategy in a demo account before applying it to live trading to gain confidence and understanding.
