//@version=4
strategy("Impulse BF 🚀", overlay=false, initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent, commission_value=0.075)

/////////////// Time Frame ///////////////
_1 = input(false,  "════════ Test Period ═══════")
testStartYear = input(2015, "Backtest Start Year") 
testStartMonth = input(1, "Backtest Start Month")
testStartDay = input(1, "Backtest Start Day")
testPeriodStart = timestamp(testStartYear,testStartMonth,testStartDay, 0, 0)

testStopYear = input(2019, "Backtest Stop Year")
testStopMonth = input(12, "Backtest Stop Month")
testStopDay = input(31, "Backtest Stop Day")
testPeriodStop = timestamp(testStopYear,testStopMonth,testStopDay, 0, 0)

testPeriod() => time >= testPeriodStart and time <= testPeriodStop ? true : false

/////////////// Impulse /////////////// 
_2 = input(false, "═════════ Impulse ══════════")
upLength = input(defval=18, title="Up Length", minval=1, maxval=1000)
downLength = input(defval=18, title="Down Length", minval=1, maxval=1000)

impulse = close - open
upImpulse = impulse > 0 ? impulse : 0
downImpulse = impulse < 0 ? -impulse : 0
totalUpImpulses = 0.0
totalDownImpulses = 0.0
totalUpImpulses := sum(upImpulse, upLength)
totalDownImpulses := sum(downImpulse, downLength)

///////////// Rate Of Change ///////////// 
_3 = input(false, "══════ Rate of Change ══════")
source = close
roclength = input(27, "ROC Length",  minval=1)
pcntChange = input(1, "ROC % Change", minval=1)
roc = 100 * (source - source[roclength]) / source[roclength]
emaroc = ema(roc, roclength / 2)
isMoving() => emaroc > (pcntChange / 2) or emaroc < (0 - (pcntChange / 2))

///////////////  Strategy  /////////////// 
long = totalUpImpulses > totalDownImpulses and isMoving()
short = totalUpImpulses < totalDownImpulses and isMoving() 

last_long = 0.0
last_short = 0.0
last_long := long ? time : nz(last_long[1])
last_short := short ? time : nz(last_short[1])

long_signal = crossover(last_long, last_short)
short_signal = crossover(last_short, last_long)

last_open_long_signal = 0.0
last_open_short_signal = 0.0
last_open_long_signal := long_signal ? open : nz(last_open_long_signal[1])
last_open_short_signal := short_signal ? open : nz(last_open_short_signal[1])

last_long_signal = 0.0
last_short_signal = 0.0
last_long_signal := long_signal ? time : nz(last_long_signal[1])
last_short_signal := short_signal ? time : nz(last_short_signal[1])

in_long_signal = last_long_signal > last_short_signal
in_short_signal = last_short_signal > last_long_signal

last_high = 0.0
last_low = 0.0
last_high := not in_long_signal ? na : in_long_signal and (na(last_high[1]) or high > nz(last_high[1])) ? high : nz(last_high[1])
last_low := not in_short_signal ? na : in_short_signal and (na(last_low[1]) or low < nz(last_low[1])) ? low : nz(last_low[1])

since_longEntry = barssince(last_open_long_signal != last_open_long_signal[1]) 
since_shortEntry = barssince(last_open_short_signal != last_open_short_signal[1]) 

//////////////// Stop loss /////////////// 
_4 = input(false, "════════ Stop Loss ═══════")
sl_inp = input(100.0, title='Stop Loss %') / 100

slLong = in_long_signal ? strategy.position_avg_price * (1 - sl_inp) : na
slShort = strategy.position_avg_price * (1 + sl_inp)
long_sl = in_long_signal ? slLong : na
short_sl = in_short_signal ? slShort : na

/////////////// Execution /////////////// 
if testPeriod()
    strategy.entry("L", strategy.long, when=long)
    strategy.entry("S", strategy.short, when=short)
    strategy.exit("L SL", "L", stop=long_sl, when=since_longEntry > 0)
    strategy.exit("S SL", "S", stop=short_sl, when=since_shortEntry > 0)

/////////////// Plotting /////////////// 
p1 = plot(series=totalUpImpulses, title="Total Up Impulses", color=color.green, linewidth=1)
p2 = plot(series=totalDownImpulses, title="Total Down Impulses", color=color.red, linewidth=1)
fill(p1, p2, color = totalDownImpulses < totalUpImpulses ? color.lime : color.red, transp=80)
bgcolor(isMoving() ? long ? color.green : short ? color.red : na : color.white, transp=80)
bgcolor(long_signal ? color.lime : short_signal ? color.red : na, transp=30)

View in Pine Editor・94 lines
Use on chart
3
1
3
1
14 709
Thanks to rasantos for the idea for this strategy.

The 2 lines are based on the sum number of impulses for x bars back. So total "up impulses" is the sum of the bars where price closed higher, and vice versa for "down impulses". The strategy is simple - a long signal is generated when the total up impulses exceeds the total down impulses. A short signal is generated when total down impulses exceeds total up impulses.

I included a rate of change function to filter out some of the sideways action, denoted by a white background.

I included the option of a stop loss since it may be useful for some settings but the default is 100% which will not be triggered. If we get stopped out and we still have the conditions for our position on candle close, we re-enter.

INSTRUCTIONS

Bright Green = go long

Bright Red = go short

Green = we have conditions for a long

Red = we have conditions for a short

White = no trade



NB: the length parameters are set to 18 by default. The higher this number, the more long term this strategy becomes. So for a macro trader, a setting of 84 would provide a small number of trades per year.
