//@version=4
strategy(shorttitle="BBands Fibo", title="Bollinger Bands Fibonacci Ratios", overlay=true)

length      =   input(20, minval=1, type=input.integer, title="Length")
src         =   input(close, title="Source")
offset      =   input(0, "Offset", type = input.integer, minval = -500, maxval = 500)
fibo1       =   input(defval=1.618, title="Fibonacci Ratio 1")
fibo2       =   input(defval=2.618, title="Fibonacci Ratio 2")
fibo3       =   input(defval=4.236, title="Fibonacci Ratio 3")

fiboBuyReverse = input(false, title = "Use Reverse Buy?")
fiboBuy       =   input(options = ["Fibo 1", "Fibo 2", "Fibo 3"],defval = "Fibo 1", title="Fibonacci Buy")
fiboSellReverse = input(false, title = "Use Reverse Sell?")
fiboSell       =   input(options = ["Fibo 1", "Fibo 2", "Fibo 3"],defval = "Fibo 1", title="Fibonacci Sell")

sma = sma(src, length)
atr = atr(length)

ratio1 = atr * fibo1
ratio2 = atr * fibo2
ratio3 = atr * fibo3

upper3 = sma + ratio3
upper2 = sma + ratio2
upper1 = sma + ratio1

lower1 = sma - ratio1
lower2 = sma - ratio2
lower3 = sma - ratio3

plot(sma, style=0, title="Basis", color=color.orange, linewidth=2, offset = offset)

upp3 = plot(upper3, transp=90, title="Upper 3", color=color.teal, offset = offset)
upp2 = plot(upper2, transp=60, title="Upper 2", color=color.teal, offset = offset)
upp1 = plot(upper1, transp=30, title="Upper 1", color=color.teal, offset = offset)

low1 = plot(lower1, transp=30, title="Lower 1", color=color.teal, offset = offset)
low2 = plot(lower2, transp=60, title="Lower 2", color=color.teal, offset = offset)
low3 = plot(lower3, transp=90, title="Lower 3", color=color.teal, offset = offset)

fill(upp3, low3, title = "Background", color=color.new(color.teal, 95))

targetBuy = fiboBuy == "Fibo 1" ? upper1 : fiboBuy == "Fibo 2" ? upper2 : upper3
targetBuy := fiboBuyReverse == false ? targetBuy : fiboBuy == "Fibo 1" ? lower1 : fiboBuy == "Fibo 2" ? lower2 : lower3
buy = low < targetBuy and high > targetBuy

targetSell = fiboSell == "Fibo 1" ? lower1 : fiboSell == "Fibo 2" ? lower2 : lower3
targetSell := fiboSellReverse == false ? targetSell : fiboSell == "Fibo 1" ? upper1 : fiboSell == "Fibo 2" ? upper2 : upper3
sell = low < targetSell and high > targetSell

strategy.entry("Buy", true, when = buy)
strategy.entry("Sell", false, when = sell)

View in Pine Editor・52 lines
Use on chart
4
6
8
12
16 928
Hello, everyone!

We have just released an innovative strategy for TradingView. It allows you to identify price pivot points and volatility.


This strategy is:

User-friendly


Configurable


Equipped with Bollinger Bands and smoothed ATR to measure volatility





Features

Thanks to the BB Fibo strategy, you can:


Trade stocks and commodities.


Identify price pivot points.


Choose any band for trading Long or Short positions.


Swap upper and lower bands applying Use Reverse Buy/Sell parameters.




Note! The upper bands are for the Long position. The lower bands are for the Short positions.


Parameters

We have equipped our strategy with more than 14 additional parameters. So, you can configure the EA according to your needs!


Inputs:
Length


Source: Open, High, Low, Close, HL2, HLC3, OHLC4


Offset


Fibonacci Ratio 1 — a Fibonacci factor for the 1st upper and lower indicator lines calculating.


Fibonacci Ratio 2 — a Fibonacci factor for the 2nd upper and lower indicator lines calculating.


Fibonacci Ratio 3 — a Fibonacci factor for the 3d upper and lower indicator lines calculating.


Use Reverse Buy — the strategy will use lower Bollinger bands instead of upper ones.


Fibonacci Buy — band selection for opening Long positions conditions.


Use Reverse Sell — the strategy will use upper Bollinger bands instead of lower ones.


Fibonacci Sell — band selection for opening Short positions conditions.

Style:
Basis — baseline color and style settings.


Upper 3 — the 3d upper line color and style.


Upper 2 — the 2nd upper line color and style.


Upper 1 — the 1st upper line color and style.


Lower 1 — the 1st lower line color and style.


Lower 2 — the 2nd lower line color and style.


Lower 3 — the 3d upper line color and style.


Background — the background color within the 3d upper and 3d lower indicator band.


Precision — the number of decimals for BB Fibo values.


Note! Try BB Fibo on your demo account first before going live.



