//@version=4
##root(root_metainfo,rm_0,'shape_arrow_up',input__string,plotshape,style)
##root(root_metainfo,rm_1,'BelowBar',input__string,plotshape,location)
##root(root_metainfo,rm_2,'normal',const__string,plotshape,size)
##root(root_metainfo,rm_3,'shape_arrow_down',input__string,plotshape,style)
##root(root_metainfo,rm_4,'AboveBar',input__string,plotshape,location)
##root(root_metainfo,rm_5,'normal',const__string,plotshape,size)
