//@version=4

//Ichimoku Inputs
ts_bars = input(9, minval=1, title="Tenkan-Sen Bars", group="Ichimoku Cloud")
ks_bars = input(26, minval=1, title="Kijun-Sen Bars", group="Ichimoku Cloud")
ssb_bars = input(52, minval=1, title="Senkou-Span B Bars", group="Ichimoku Cloud")
cs_offset = input(26, minval=1, title="Chikou-Span Offset", group="Ichimoku Cloud")
ss_offset = input(26, minval=1, title="Senkou-Span Offset", group="Ichimoku Cloud")
trade_long = input(true, title="Long Entry", group="Ichimoku Cloud")
trade_short = input(true, title="Short Entry", group="Ichimoku Cloud")
// REMOVED wait_for_cloud = input(true, title="Wait for Cloud Confirmation", group="Ichimoku Cloud")
//TODO: Add option to TP on Chikou Span Cross
//tp_on_chikou_cross = input(false, title="Exit Deal on Chikou Cross")

//Stop Loss Inputs
use_short_stop_loss = input(false, title="Short Stop Loss", group="Stop Loss and Take Profit", inline="Short_SL")
short_stop_loss = input(title="(%)", type=input.float, minval=0.0, step=0.1, 
     defval=5, group="Stop Loss and Take Profit", inline="Short_SL") * 0.01
use_long_stop_loss = input(false, title="Long Stop Loss", group="Stop Loss and Take Profit", inline="Long_SL")
long_stop_loss = input(title="(%)", type=input.float, minval=0.0, step=0.1, 
     defval=5, group="Stop Loss and Take Profit", inline="Long_SL") * 0.01

//Take Profit Inputs     
use_short_take_profit = input(false, title="Short Take Profit", group="Stop Loss and Take Profit", inline="Short_TP")
short_take_profit = input(title="(%)", type=input.float, minval=0.0, step=0.1,
     defval = 20, group="Stop Loss and Take Profit", inline="Short_TP") * .01
use_long_take_profit = input(false, title="Long Take Profit", group="Stop Loss and Take Profit", inline="Long_TP")
long_take_profit = input(title="(%)", type=input.float, minval=0.0, step=0.1,
     defval = 20, group="Stop Loss and Take Profit", inline="Long_TP") * .01

//RSI Inputs
use_rsi_entry = input(false, title="Use for Entry", group="RSI")
use_rsi_tp = input(false, title="Use for Take Profit", group="RSI")
//seq_rsi = input(defval=1, title="TP after X Sequential bars past RSI", type=input.integer)
rsi_period = input(defval=7, title="RSI Period", type=input.integer, group="RSI")
overbought_rsi = input(defval=80, title="Overbought Level", type=input.float, group="RSI")
oversold_rsi = input(defval=20, title="Oversold Level", type=input.float, group="RSI")
//toggle_stoch_rsi = input(defval=false, 
//     title="Toggle RSI inputs to use Stoch RSI(experimental)")
//stoch_rsi_length = input(defval=7, title="Stoch RSI Length")

//Account for removal of Sequential RSI and Stoch RSI inputs.
seq_rsi = 1
toggle_stoch_rsi = false

// === INPUT SHOW PLOT ===
showDate  = input(defval = false, title = "Show Date Range", type = input.bool, group="Date Range")
start = input(defval = timestamp("01 Jan 2019 00:00 +0000"), title = "Start", type = input.time, group="Date Range", inline="Start Date")
finish = input(defval = timestamp("31 Dec 2021 23:59 +0000"), title = "End", type = input.time, group="Date Range", inline="End Date")


    
window()  => time >= start and time <= finish ? true : false     // create function "within window of time"

middle(len) => avg(lowest(len), highest(len))

// Ichimoku Components
tenkan = middle(ts_bars)
kijun = middle(ks_bars)
senkouA = avg(tenkan, kijun)
senkouB = middle(ssb_bars)
chikou = close[cs_offset]

bgcolor(color = showDate and window() ? color.gray : na, transp = 90)  // plot within time window

// Plot Ichimoku Kinko Hyo
plot(tenkan, color=#0496ff, title="Tenkan-Sen")
plot(kijun, color=#991515, title="Kijun-Sen")
plot(chikou, color=#caeb36, title="Chikou-Span")
sa=plot(senkouA, offset=ss_offset, color=color.green, title="Senkou-Span A")
sb=plot(senkouB, offset=ss_offset, color=color.red, title="Senkou-Span B")
fill(sa, sb, color = senkouA > senkouB ? color.green : color.red, title="Cloud color")

ss_high = max(senkouA[ss_offset], senkouB[ss_offset])
ss_low = min(senkouA[ss_offset], senkouB[ss_offset])

// Long and Short Signals
// This was updated to specifically be the crossover and crossunder since this is the main alert for Ichimoku; not just the confirmation.
// The rest of the pieces of Ichimoku are used for confirmation in this indicator
tk_cross_bull = crossover(tenkan, kijun)
tk_cross_bear = crossunder(tenkan, kijun)
// Entry/Exit Confirmation
cs_cross_bull = mom(close, cs_offset) > 0
cs_cross_bear = mom(close, cs_offset) < 0
price_above_kumo = close > ss_high
price_below_kumo = close < ss_low
senkou_green = senkouA > senkouB ? true : false
rsi1 = rsi(close, rsi_period)

rsi_value = toggle_stoch_rsi ? stoch(rsi1, rsi1, rsi1, rsi_period) : rsi1

in_long = false
in_long := in_long[1]
in_short = false
in_short := in_short[1]

long_entry = tk_cross_bull and cs_cross_bull and price_above_kumo and senkou_green and not in_long
short_entry = tk_cross_bear and cs_cross_bear and price_below_kumo and not senkou_green and not in_short
long_exit = short_entry and in_long
short_exit = long_entry and in_short

// We use the condition of > or < for underbought and undersold because they are being used for additional confirmation
// Use the crossover on the overbought and oversold conditions because they are used for take profit without Ichimoku

overbought = crossover(rsi_value, overbought_rsi)
oversold = crossunder(rsi_value, oversold_rsi)
underbought = rsi_value < overbought_rsi
undersold = rsi_value > oversold_rsi

if (use_rsi_entry)
    long_entry := long_entry and underbought
    short_entry := short_entry and undersold

if (use_rsi_tp)
    long_exit := overbought and in_long
    short_exit := oversold and in_short

// The following logic exists to keep RSI TP from firing when you aren't already in a long or short
// It may be used late to control other TP conditions
if (long_entry)
    in_long := true
    in_short := false

if (long_exit)
    in_long := false
if (short_entry)
    in_short := true
    in_long := false
if (short_exit)
    in_short := false

longStopPrice  = strategy.position_avg_price * (1 - long_stop_loss)
shortStopPrice = strategy.position_avg_price * (1 + short_stop_loss)
longLimitPrice = strategy.position_avg_price * (1 + long_take_profit)
shortLimitPrice = strategy.position_avg_price * (1 - short_take_profit)

strategy.entry("Long", strategy.long, when=long_entry and trade_long and  (showDate ? window() : true))
strategy.entry("Short", strategy.short, when=short_entry and trade_short  and (showDate ? window() : true))

if (strategy.position_size > 0.0)
    if (use_long_stop_loss and not use_long_take_profit)
        strategy.exit("Long", stop = longStopPrice)
    if (use_long_take_profit and not use_long_stop_loss)
        strategy.exit("Long", limit = longLimitPrice)
    if (use_long_take_profit and use_long_stop_loss)
        strategy.exit("Long", stop = longStopPrice, limit=longLimitPrice)
if (strategy.position_size < 0.0)
    if (use_short_stop_loss and not use_short_take_profit)
        strategy.exit("Short", stop = shortStopPrice)
    if (use_short_take_profit and not use_short_stop_loss)
        strategy.exit("Short", limit = shortLimitPrice)
    if (use_short_take_profit and use_short_stop_loss)
        strategy.exit("Short", stop = shortStopPrice, limit = shortLimitPrice)

strategy.close("Long", when=long_exit and (showDate ? window() : true))
strategy.close("Short", when=short_exit and (showDate ? window() : true))

View in Pine Editor・159 lines
Use on chart
8
3
7
22
30 578
Feb 12, 2021
Started with the Basic Ichimoku strategy from Mizuki32. Added Take Profit, Stop Loss (for both long and short), and a toggle to wait for confirmation from the cloud.
Feb 20, 2021
Release Notes
Added RSI options for Entry and TP.
Feb 20, 2021
Release Notes
Added option to take profit after X bar closes past the RSI threshold.
Feb 21, 2021
Release Notes
Updating defaults to have no RSI, no TP, no SL
Mar 8, 2021
Release Notes
Updated Backtester to have toggle for Stoch RSI and cleaned up RSI logic on strategy exit.
May 30, 2021
Release Notes
Cleaning up Inputs, Removing Stochastic RSI, removing TP after sequential RSI
Jun 8, 2021
Release Notes
Added back Stoch RSI Toggle per user request. Moved date range to top so the data selector is usable.
Apr 15, 2023
Release Notes
This update cleans up the code and corrects many bugs. It is recommended you update your strategy and the matching indicator.

MAJOR BUGFIXES:
1. Corrected logic for tenkan and kijun cross to use crossover and crossunder fuctions. This prevents possible misfiring of alerts
2. Corrected RSI and Long/Short logic so RSI TP fires correctly.
3. Correct the Chikou Span Plotting (it was plotting in the wrong direction of the current price).
4. Corrected offsets. Previous indicator that logic was sourced from incorrect offset everything by +1
Apr 15, 2023
Release Notes
Updated the color of the chikou span so it's easier to see.
Apr 15, 2023
Release Notes
Fixing entry and exit logic from update
Apr 15, 2023
Release Notes
Updating name and cleaning up some logic
Apr 16, 2023
Release Notes
Fixed broken short entry logic
