//@version=3
//Created by 100kiwi
strategy(title = "TrapTrading", overlay = true, pyramiding = 110000)

/////////////////////////////////////////////////////////////////////
// COMPONENT CODE START
//*******************************************************************
// Backtesting Period Selector | Component by pbergden
//*******************************************************************
testStartYear = input(2015, "Backtest Start Year")
testStartMonth = input(1, "Backtest Start Month")
testStartDay = input(1, "Backtest Start Day")
testPeriodStart = timestamp(testStartYear,testStartMonth,testStartDay,0,0)

testStopYear = input(2018, "Backtest Stop Year")
testStopMonth = input(12, "Backtest Stop Month")
testStopDay = input(31, "Backtest Stop Day")
testPeriodStop = timestamp(testStopYear,testStopMonth,testStopDay,0,0)

// A switch to control background coloring of the test period
testPeriodBackground = input(title="Color Background?", type=bool, defval=true)
testPeriodBackgroundColor = testPeriodBackground and (time >= testPeriodStart) and (time <= testPeriodStop) ? #00FF00 : na
bgcolor(testPeriodBackgroundColor, transp=97)

testPeriod() =>
    time >= testPeriodStart and time <= testPeriodStop ? true : false
// COMPONENT CODE STOP
/////////////////////////////////////////////////////////////////////

// input
buySide = input(defval = true, title = "Trade Direction (ON: Buy Side OFF: Sell Side)", type = bool)
counterTrend  = input(defval = false, title = "Trade Mode (ON: Counter Trend OFF: Trend Following)", type = bool)
buyEqualAmounts  = input(defval = false, title = "Buy Equal Amounts?", type = bool)
profitMargin = input(defval = 5, title = "Profit Margin (1-5)", type = integer, minval = 1, maxval = 5)
len1 = input(defval = 20, title = "Period (1-200)", type = integer, minval = 1, maxval = 200)
multiple = input(defval = 0.7, title = "Multiple", type = float)

m1 = close - close[len1]
controlPoint = counterTrend ? lowest(abs(m1), len1) == abs(m1) : highest(abs(m1), len1) == abs(m1)
baseLine = valuewhen(controlPoint, avg(close, close[len1]), 0)

// trap line
atr = valuewhen(controlPoint, highest(max(max(atr(len1), atr(len1 * 2)), atr(len1 * 3)), len1), 0)
line1Up = baseLine + (atr * multiple)
line2Up = baseLine + (atr * 2 * multiple)
line3Up = baseLine + (atr * 3 * multiple)
line4Up = baseLine + (atr * 4 * multiple)
line5Up = baseLine + (atr * 5 * multiple)
line6Up = baseLine + (atr * 6 * multiple)
line7Up = baseLine + (atr * 7 * multiple)
line8Up = baseLine + (atr * 8 * multiple)
line9Up = baseLine + (atr * 9 * multiple)
line10Up = baseLine + (atr * 10 * multiple)
line1Down = baseLine - (atr * multiple)
line2Down = baseLine - (atr * 2 * multiple)
line3Down = baseLine - (atr * 3 * multiple)
line4Down = baseLine - (atr * 4 * multiple)
line5Down = baseLine - (atr * 5 * multiple)
line6Down = baseLine - (atr * 6 * multiple)
line7Down = baseLine - (atr * 7 * multiple)
line8Down = baseLine - (atr * 8 * multiple)
line9Down = baseLine - (atr * 9 * multiple)
line10Down = baseLine - (atr * 10 * multiple)

// draw
barcolor(controlPoint ? yellow : (close >= baseLine ? teal : red), title = "Candle Color")

plot(baseLine, title = "Base Line", color = white, linewidth = 4, style = stepline, transp = 0)
plot(line1Up, title = "1Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line2Up, title = "2Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line3Up, title = "3Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line4Up, title = "4Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line5Up, title = "5Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line6Up, title = "6Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line7Up, title = "7Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line8Up, title = "8Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line9Up, title = "9Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line10Up, title = "10Up Line", color = green, linewidth = 1, style = stepline, transp = 0)
plot(line1Down, title = "1Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line2Down, title = "2Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line3Down, title = "3Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line4Down, title = "4Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line5Down, title = "5Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line6Down, title = "6Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line7Down, title = "7Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line8Down, title = "8Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line9Down, title = "9Down Line", color = red, linewidth = 1, style = stepline, transp = 0)
plot(line10Down, title = "10Down Line", color = red, linewidth = 1, style = stepline, transp = 0)

exitLong0 = profitMargin == 1 ? line1Up : profitMargin == 2 ? line2Up : profitMargin == 3 ? line3Up : profitMargin == 4 ? line4Up : profitMargin == 5 ? line5Up : line6Up
exitLong1 = profitMargin == 1 ? baseLine : profitMargin == 2 ? line1Up : profitMargin == 3 ? line2Up : profitMargin == 4 ? line3Up : profitMargin == 5 ? line4Up : line5Up
exitLong2 = profitMargin == 1 ? line1Down : profitMargin == 2 ? baseLine : profitMargin == 3 ? line1Up : profitMargin == 4 ? line2Up : profitMargin == 5 ? line3Up : line4Up
exitLong3 = profitMargin == 1 ? line2Down : profitMargin == 2 ? line1Down : profitMargin == 3 ? baseLine : profitMargin == 4 ? line1Up : profitMargin == 5 ? line2Up : line3Up
exitLong4 = profitMargin == 1 ? line3Down : profitMargin == 2 ? line2Down : profitMargin == 3 ? line1Down : profitMargin == 4 ? baseLine : profitMargin == 5 ? line1Up : line2Up
exitLong5 = profitMargin == 1 ? line4Down : profitMargin == 2 ? line3Down : profitMargin == 3 ? line2Down : profitMargin == 4 ? line1Down : profitMargin == 5 ? baseLine : line1Up
exitLong6 = profitMargin == 1 ? line5Down : profitMargin == 2 ? line4Down : profitMargin == 3 ? line3Down : profitMargin == 4 ? line2Down : profitMargin == 5 ? line1Down : baseLine
exitLong7 = profitMargin == 1 ? line6Down : profitMargin == 2 ? line5Down : profitMargin == 3 ? line4Down : profitMargin == 4 ? line3Down : profitMargin == 5 ? line2Down : line1Down
exitLong8 = profitMargin == 1 ? line7Down : profitMargin == 2 ? line6Down : profitMargin == 3 ? line5Down : profitMargin == 4 ? line4Down : profitMargin == 5 ? line3Down : line2Down
exitLong9 = profitMargin == 1 ? line8Down : profitMargin == 2 ? line7Down : profitMargin == 3 ? line6Down : profitMargin == 4 ? line5Down : profitMargin == 5 ? line4Down : line3Down
exitLong10 = profitMargin == 1 ? line9Down : profitMargin == 2 ? line8Down : profitMargin == 3 ? line7Down : profitMargin == 4 ? line6Down : profitMargin == 5 ? line5Down : line4Down

exitShort0 = profitMargin == 1 ? line1Down : profitMargin == 2 ? line2Down : profitMargin == 3 ? line3Down : profitMargin == 4 ? line4Down : profitMargin == 5 ? line5Down : line6Down
exitShort1 = profitMargin == 1 ? baseLine : profitMargin == 2 ? line1Down : profitMargin == 3 ? line2Down : profitMargin == 4 ? line3Down : profitMargin == 5 ? line4Down : line5Down
exitShort2 = profitMargin == 1 ? line1Up : profitMargin == 2 ? baseLine : profitMargin == 3 ? line1Down : profitMargin == 4 ? line2Down : profitMargin == 5 ? line3Down : line4Down
exitShort3 = profitMargin == 1 ? line2Up : profitMargin == 2 ? line1Up : profitMargin == 3 ? baseLine : profitMargin == 4 ? line1Down : profitMargin == 5 ? line2Down : line3Down
exitShort4 = profitMargin == 1 ? line3Up : profitMargin == 2 ? line2Up : profitMargin == 3 ? line1Up : profitMargin == 4 ? baseLine : profitMargin == 5 ? line1Down : line2Down
exitShort5 = profitMargin == 1 ? line4Up : profitMargin == 2 ? line3Up : profitMargin == 3 ? line2Up : profitMargin == 4 ? line1Up : profitMargin == 5 ? baseLine : line1Down
exitShort6 = profitMargin == 1 ? line5Up : profitMargin == 2 ? line4Up : profitMargin == 3 ? line3Up : profitMargin == 4 ? line2Up : profitMargin == 5 ? line1Up : baseLine
exitShort7 = profitMargin == 1 ? line6Up : profitMargin == 2 ? line5Up : profitMargin == 3 ? line4Up : profitMargin == 4 ? line3Up : profitMargin == 5 ? line2Up : line1Up
exitShort8 = profitMargin == 1 ? line7Up : profitMargin == 2 ? line6Up : profitMargin == 3 ? line5Up : profitMargin == 4 ? line4Up : profitMargin == 5 ? line3Up : line2Up
exitShort9 = profitMargin == 1 ? line8Up : profitMargin == 2 ? line7Up : profitMargin == 3 ? line6Up : profitMargin == 4 ? line5Up : profitMargin == 5 ? line4Up : line3Up
exitShort10 = profitMargin == 1 ? line9Up : profitMargin == 2 ? line8Up : profitMargin == 3 ? line7Up : profitMargin == 4 ? line6Up : profitMargin == 5 ? line5Up : line4Up

// strategy code
if testPeriod() and buySide
    if buyEqualAmounts
        strategy.exit("Exit Long0", from_entry = "Long0", qty = 10000, limit = exitLong0)
        strategy.exit("Exit Long1", from_entry = "Long1", qty = 10000, limit = exitLong1)
        strategy.exit("Exit Long2", from_entry = "Long2", qty = 10000, limit = exitLong2)
        strategy.exit("Exit Long3", from_entry = "Long3", qty = 10000, limit = exitLong3)
        strategy.exit("Exit Long4", from_entry = "Long4", qty = 10000, limit = exitLong4)
        strategy.exit("Exit Long5", from_entry = "Long5", qty = 10000, limit = exitLong5)
        strategy.exit("Exit Long6", from_entry = "Long6", qty = 10000, limit = exitLong6)
        strategy.exit("Exit Long7", from_entry = "Long7", qty = 10000, limit = exitLong7)
        strategy.exit("Exit Long8", from_entry = "Long8", qty = 10000, limit = exitLong8)
        strategy.exit("Exit Long9", from_entry = "Long9", qty = 10000, limit = exitLong9)
        strategy.exit("Exit Long10", from_entry = "Long10", qty = 10000, limit = exitLong10)
        strategy.order("Long0", strategy.long, qty = 10000, limit = baseLine, when = strategy.position_size <= 0)
        strategy.order("Long1", strategy.long, qty = 10000, limit = line1Down, when = strategy.position_size <= 10000)
        strategy.order("Long2", strategy.long, qty = 10000, limit = line2Down, when = strategy.position_size <= 20000)
        strategy.order("Long3", strategy.long, qty = 10000, limit = line3Down, when = strategy.position_size <= 30000)
        strategy.order("Long4", strategy.long, qty = 10000, limit = line4Down, when = strategy.position_size <= 40000)
        strategy.order("Long5", strategy.long, qty = 10000, limit = line5Down, when = strategy.position_size <= 50000)
        strategy.order("Long6", strategy.long, qty = 10000, limit = line6Down, when = strategy.position_size <= 60000)
        strategy.order("Long7", strategy.long, qty = 10000, limit = line7Down, when = strategy.position_size <= 70000)
        strategy.order("Long8", strategy.long, qty = 10000, limit = line8Down, when = strategy.position_size <= 80000)
        strategy.order("Long9", strategy.long, qty = 10000, limit = line9Down, when = strategy.position_size <= 90000)
        strategy.order("Long10", strategy.long, qty = 10000, limit = line10Down, when = strategy.position_size <= 100000)
    else
        strategy.exit("Exit Long0", from_entry = "Long0", qty = 5000, limit = exitLong0)
        strategy.exit("Exit Long1", from_entry = "Long1", qty = 6000, limit = exitLong1)
        strategy.exit("Exit Long2", from_entry = "Long2", qty = 7000, limit = exitLong2)
        strategy.exit("Exit Long3", from_entry = "Long3", qty = 8000, limit = exitLong3)
        strategy.exit("Exit Long4", from_entry = "Long4", qty = 9000, limit = exitLong4)
        strategy.exit("Exit Long5", from_entry = "Long5", qty = 10000, limit = exitLong5)
        strategy.exit("Exit Long6", from_entry = "Long6", qty = 11000, limit = exitLong6)
        strategy.exit("Exit Long7", from_entry = "Long7", qty = 12000, limit = exitLong7)
        strategy.exit("Exit Long8", from_entry = "Long8", qty = 13000, limit = exitLong8)
        strategy.exit("Exit Long9", from_entry = "Long9", qty = 14000, limit = exitLong9)
        strategy.exit("Exit Long10", from_entry = "Long10", qty = 15000, limit = exitLong10)
        strategy.order("Long0", strategy.long, qty = 5000, limit = baseLine, when = strategy.position_size <= 0)
        strategy.order("Long1", strategy.long, qty = 6000, limit = line1Down, when = strategy.position_size <= 5000)
        strategy.order("Long2", strategy.long, qty = 7000, limit = line2Down, when = strategy.position_size <= 11000)
        strategy.order("Long3", strategy.long, qty = 8000, limit = line3Down, when = strategy.position_size <= 18000)
        strategy.order("Long4", strategy.long, qty = 9000, limit = line4Down, when = strategy.position_size <= 26000)
        strategy.order("Long5", strategy.long, qty = 10000, limit = line5Down, when = strategy.position_size <= 35000)
        strategy.order("Long6", strategy.long, qty = 11000, limit = line6Down, when = strategy.position_size <= 45000)
        strategy.order("Long7", strategy.long, qty = 12000, limit = line7Down, when = strategy.position_size <= 56000)
        strategy.order("Long8", strategy.long, qty = 13000, limit = line8Down, when = strategy.position_size <= 68000)
        strategy.order("Long9", strategy.long, qty = 14000, limit = line9Down, when = strategy.position_size <= 81000)
        strategy.order("Long10", strategy.long, qty = 15000, limit = line10Down, when = strategy.position_size <= 95000)
else
    if testPeriod() and not buySide
        if buyEqualAmounts
            strategy.exit("Exit Short0", from_entry = "Short0", qty = 10000, limit = exitShort0)
            strategy.exit("Exit Short1", from_entry = "Short1", qty = 10000, limit = exitShort1)
            strategy.exit("Exit Short2", from_entry = "Short2", qty = 10000, limit = exitShort2)
            strategy.exit("Exit Short3", from_entry = "Short3", qty = 10000, limit = exitShort3)
            strategy.exit("Exit Short4", from_entry = "Short4", qty = 10000, limit = exitShort4)
            strategy.exit("Exit Short5", from_entry = "Short5", qty = 10000, limit = exitShort5)
            strategy.exit("Exit Short6", from_entry = "Short6", qty = 10000, limit = exitShort6)
            strategy.exit("Exit Short7", from_entry = "Short7", qty = 10000, limit = exitShort7)
            strategy.exit("Exit Short8", from_entry = "Short8", qty = 10000, limit = exitShort8)
            strategy.exit("Exit Short9", from_entry = "Short9", qty = 10000, limit = exitShort9)
            strategy.exit("Exit Short10", from_entry = "Short10", qty = 10000, limit = exitShort10)
            strategy.order("Short0", strategy.short, qty = 10000, limit = baseLine, when = strategy.position_size >= 0)
            strategy.order("Short1", strategy.short, qty = 10000, limit = line1Up, when = strategy.position_size >= -10000)
            strategy.order("Short2", strategy.short, qty = 10000, limit = line2Up, when = strategy.position_size >= -20000)
            strategy.order("Short3", strategy.short, qty = 10000, limit = line3Up, when = strategy.position_size >= -30000)
            strategy.order("Short4", strategy.short, qty = 10000, limit = line4Up, when = strategy.position_size >= -40000)
            strategy.order("Short5", strategy.short, qty = 10000, limit = line5Up, when = strategy.position_size >= -50000)
            strategy.order("Short6", strategy.short, qty = 10000, limit = line6Up, when = strategy.position_size >= -60000)
            strategy.order("Short7", strategy.short, qty = 10000, limit = line7Up, when = strategy.position_size >= -70000)
            strategy.order("Short8", strategy.short, qty = 10000, limit = line8Up, when = strategy.position_size >= -80000)
            strategy.order("Short9", strategy.short, qty = 10000, limit = line9Up, when = strategy.position_size >= -90000)
            strategy.order("Short10", strategy.short, qty = 10000, limit = line10Up, when = strategy.position_size >= -100000)
        else
            strategy.exit("Exit Short0", from_entry = "Short0", qty = 5000, limit = exitShort0)
            strategy.exit("Exit Short1", from_entry = "Short1", qty = 6000, limit = exitShort1)
            strategy.exit("Exit Short2", from_entry = "Short2", qty = 7000, limit = exitShort2)
            strategy.exit("Exit Short3", from_entry = "Short3", qty = 8000, limit = exitShort3)
            strategy.exit("Exit Short4", from_entry = "Short4", qty = 9000, limit = exitShort4)
            strategy.exit("Exit Short5", from_entry = "Short5", qty = 10000, limit = exitShort5)
            strategy.exit("Exit Short6", from_entry = "Short6", qty = 11000, limit = exitShort6)
            strategy.exit("Exit Short7", from_entry = "Short7", qty = 12000, limit = exitShort7)
            strategy.exit("Exit Short8", from_entry = "Short8", qty = 13000, limit = exitShort8)
            strategy.exit("Exit Short9", from_entry = "Short9", qty = 14000, limit = exitShort9)
            strategy.exit("Exit Short10", from_entry = "Short10", qty = 15000, limit = exitShort10)
            strategy.order("Short0", strategy.short, qty = 5000, limit = baseLine, when = strategy.position_size >= 0)
            strategy.order("Short1", strategy.short, qty = 6000, limit = line1Up, when = strategy.position_size >= -5000)
            strategy.order("Short2", strategy.short, qty = 7000, limit = line2Up, when = strategy.position_size >= -11000)
            strategy.order("Short3", strategy.short, qty = 8000, limit = line3Up, when = strategy.position_size >= -18000)
            strategy.order("Short4", strategy.short, qty = 9000, limit = line4Up, when = strategy.position_size >= -26000)
            strategy.order("Short5", strategy.short, qty = 10000, limit = line5Up, when = strategy.position_size >= -35000)
            strategy.order("Short6", strategy.short, qty = 11000, limit = line6Up, when = strategy.position_size >= -45000)
            strategy.order("Short7", strategy.short, qty = 12000, limit = line7Up, when = strategy.position_size >= -56000)
            strategy.order("Short8", strategy.short, qty = 13000, limit = line8Up, when = strategy.position_size >= -68000)
            strategy.order("Short9", strategy.short, qty = 14000, limit = line9Up, when = strategy.position_size >= -81000)
            strategy.order("Short10", strategy.short, qty = 15000, limit = line10Up, when = strategy.position_size >= -95000)

View in Pine Editor・209 lines
Use on chart
2
7
5
5
13 518
Aug 19, 2018
Buy on dips and sell into rallies. Simple as that.

- Short line (green)
- Base line (white)
- Long line (red)

When the market price touches the white or the red(green) lines, buy(sell) orders are generated.
The exit points are 2 lines above(below) the entries.

Parameters
- Period: It affects the value of Base line and the spacing of each line.
- Multiple: Specify the spacing between each line.
Aug 19, 2018
Release Notes
- bug fix
- add a setting "Color Bars"
Aug 20, 2018
Release Notes

- Add "Profit Margin". If "1" is set to this parameter, exit long(short) points are "1" line above(below) the entries.
- Add "Buy Equal Amounts?".
- Remove "Color Bar". (Bar color can be changed in the style tab.)
- Modify default values.
Aug 21, 2018
Release Notes
Fix a typo.
Aug 23, 2018
Release Notes
modify default values
Sep 5, 2018
Release Notes
modify default values etc.
