//@version=4
strategy("EMA Slope AyE", shorttitle = "SLOPE", overlay=false)
EMAPeriod = input(20, title = "EMA Period", type = input.integer)
SlopePeriod = input(1, title = "Slope Period", type = input.integer)

EMA = ema(close, EMAPeriod)
Slope = (EMA - EMA[SlopePeriod]) / SlopePeriod

plot(Slope, color = color.yellow, linewidth = 2)
zero = hline(0, "zero", color=#787B86)

View in Pine Editor・13 lines
Use on chart
7
1
3 212
We create our own indicator to calculate the slope of a 20 period EMA over the last candle.
