//@version=4
strategy(title="[mdeacey] EMA% Channel + BB Range Strategy v3", shorttitle="[mdeacey] EMA% Channel + BB Range Strategy v3", overlay=true)

//EMA 200

len = input(title="EMA Length", type=input.integer, defval=200)
srce = input(title="EMA Source", type=input.source, defval=close)

ema1= ema(srce,len)

percent = input(title="Channel Percentage (%)", type=input.float, defval= 1) 
valuee = (percent*ema1)/100
upperbande = ema1 + valuee
lowerbande = ema1 - valuee


plot(ema1, title='EMA200', color=color.gray, linewidth=1, style=plot.style_line )
plot(upperbande, title='EMA Upper Band', color=color.gray, linewidth=1, style=plot.style_line )
plot(lowerbande, title='EMA Lower Band', color=color.gray, linewidth=1, style=plot.style_line )

length = input(20, minval=2)
src = input(close, title="Close price")
mult = input(2.0, minval=0.001, maxval=50)

MA2 = sma(src, length)
dev = mult * stdev(src, length)
upper = MA2 + dev
lower = MA2 - dev

signalColor = crossunder(close, upper) ? color.red : crossover(close, lower) ? color.green : color.white

barcolor(color=signalColor)


upperBand = plot(upper, color=color.gray, linewidth=1)
lowerBand = plot(lower, color=color.gray, linewidth=1)
fill(upperBand, lowerBand,color=color.gray)

//Inputs
atrPeriod = input(defval=14, title="ATR Period",group='ATR Settings', type=input.integer) // Adjust this to change the ATR calculation length
multiplierPeriod = input(defval=1.75, title="ATR Multiplier Period",group='ATR Settings',  type=input.float)// Adjust this to change the distance between your candles and the line

//ATR Calculation
pine_rma(x, y) =>
    alpha = y
    sum = 0.0
    sum := (x + (alpha - 1) * nz(sum[1])) / alpha

true_range() =>
    max(high - low, max(abs(high - close[1]), abs(low - close[1])))

//Long SL
plot(low - pine_rma(true_range() * multiplierPeriod, atrPeriod), "Long Stop", color=color.red, offset = 1)
// Short SL
plot(high +pine_rma(true_range() * multiplierPeriod, atrPeriod), "Short Stop", color=color.red, offset = 1)

//////rsi
srcr = close
lenr = input(14, minval=1,group='RSI_setting', title="Length")
up = rma(max(change(srcr), 0), lenr)
down = rma(-min(change(srcr), 0), lenr)
rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - 100 / (1 + up / down)

//coloring method below

src1 = close
len1 = input(70, minval=1, title="UpLevel")
src2 = close
len2 = input(30, minval=1, title="DownLevel")
isup() =>rsi > len1
isdown() =>rsi < len2
isdown_1 = isdown()
barcolor(isup() ? color.green : isdown_1 ? color.red : na)
////////
strategy.entry("Long",true,when = (crossover(close,lower)  or crossover(close[1],lower) ) and close <upperbande and close>lowerbande and close<ema1 and not(  isdown_1 ) ) 
strategy.close("Long",when = crossunder(close,lowerbande) or crossover(close,upper) )
strategy.entry("Short",false,when = ( crossunder(close,upper) or crossunder(close[1],upper) )  and close <upperbande and close>lowerbande  and close>ema1  and not( isup() ))
strategy.close("Short",when = crossover(close,upperbande) or crossunder(close,lower) )

strategy.exit("Exit Long","Long" ,stop = low - pine_rma(true_range() * multiplierPeriod, atrPeriod) )
strategy.exit("Exit Short","Short" ,stop =high +pine_rma(true_range() * multiplierPeriod, atrPeriod)   )

View in Pine Editor・81 lines
Use on chart
5
9
2
3 459
Dec 24, 2021
This strategy is based off the users selection of an EMA and percentage defined channel. The strategy longs when a red "reversal candle" (that exceeds the averages of 3 and 9 above the EMA 3) is found until such time that either the price goes outside the Bollinger Band or the green reversal candle is found. The same but opposite process for shorts. If the price begins trending and moves outside the channel all trades are exited to prevent loss.

For trending markets the sister strategy ("[mdeacey] EMA% Channel + Bollinger Band Trending Strategy") should instead be used.



The obvious fallback to this strategy is that:
- If the bands are too wide we don't have a good definition of trending vs ranging and the price can move up/down significantly and trend whilst remaining within the ranging channel. We try to mitigate this through use of a stoploss defined by ATR and a pretty tight channel. This is a tightrope exercise as making the percentage channels tighter misses earlier entries in optimal cases. Change the parameters to find an EMA and percentages to find the best R/R in your case.

Potential further iteration:
- It would be good to see if the R/R changes positively if we only allow shorts above the EMA and longs below it.

All options are configurable and code open source. Happy trading!
Dec 27, 2021
Release Notes
Update:
- Now only allowing shorts above the EMA and longs below it. R/R increased!
Dec 29, 2021
Release Notes
Strategy now includes the use of glaz's "RSI Candles" indicator (tradingview.com/script/RADlhsKE-RSI-Candles/). The basis for including this indicator into the strategy is to delay position entries if red/green RSI candles are found with the hope to remove entries that ride the bollinger band and end up getting stopped out - decreasing the total number of trades but increasing both profitability and rate of return. This update also closes trades when the opposite bollinger band is crossed on close as I noticed this causing a number of entries to be closed too early in their move.
