//@version=4
strategy("QS - Intraday", overlay=true, calc_on_every_tick = false,pyramiding=0)

// ********** Strategy inputs - Start **********

// Used for intraday handling
// Session value should be from market start to the time you want to square-off 
// your intraday strategy
// Important: The end time should be at least 2 minutes before the intraday
// square-off time set by your broker
var i_marketSession = input(title="Market session", type=input.session, 
     defval="0915-1455", confirm=true)


rsiPreiod = input(14, title="RSI Period", type=input.integer)
rsiBuy = input(50, title="Buy when RSI is above", type=input.integer)
rsiSell = input(50, title="Sell when RSI is Bellow", type=input.integer)
isReversal = input(true, title="Exit on VWap Reversal ?", type=input.bool)

// ********** Strategy inputs - End **********


// ********** Supporting functions - Start **********

// A function to check whether the bar or period is in intraday session
barInSession(sess) => time(timeframe.period, sess) != 0

// ********** Supporting functions - End **********


// ********** Strategy - Start **********

o=(open[1]+close[1])/2
h=max(high,close,o) 
l=min(low,close,o)
c=(open+high+low+close)/4

//additional conditions to improve the % profitablilty
greenCandle = (close > open)
redCandle = (close < open)
vol = volume > volume[1]

// See if intraday session is active
bool intradaySession = barInSession(i_marketSession)

// Trade only if intraday session is active
//long and short conditions
longCondition = vwap > vwap[1]  and rsi(close,rsiPreiod)>rsiBuy and intradaySession
if (longCondition)
    strategy.entry("Buy", strategy.long)

shortCondition =  vwap < vwap[1] and rsi(close,rsiPreiod)<rsiSell and intradaySession
if (shortCondition)
    strategy.entry("Sell", strategy.short)
if(isReversal)
    strategy.close("Buy", when = vwap < vwap[1] ,comment = "ExitBuy")
    strategy.close("Sell", when =vwap > vwap[1], comment = "ExitSell")

// Square-off position (when session is over and position is open)
squareOff = (not intradaySession) and (strategy.position_size != 0)
strategy.close_all(when = squareOff, comment = "Square-off")

// ********** Strategy - End **********

View in Pine Editor・67 lines
Use on chart
7
8
3 874
This is a simple intraday strategy using very basic intraday super indicators - RSI & VWAP for working on Stocks . You can modify the values on the stock and see what are your best picks. Comment below if you found something with good returns

Strategy:
Indicators used :
The Relative Strength Index (RSI) is one of the most popular and widely used momentum oscillators.The values of the RSI oscillator, typically measured over a 14-day period, fluctuate between zero and 100. The Relative Strength Index indicates oversold market conditions when below 30 and overbought market conditions when above 70

VWAP identifies the true average price of a stock by factoring the volume of transactions at a specific price point and not based on the closing price. VWAP can add more value than your standard 10, 50, or 200 moving average indicators because VWAP reacts to price movements based on the volume during a given period.

Buying happens at VWAP Breakouts which is then validated with RSI to check for overbought & oversold conditions.
Aggressive trade stop can be employed by using the % for long and shorts in the strategy.


Usage & Best setting :
Choose a good volatile stock and a time frame - 10m.
RSI : 9
Overbought & Oversold - can be varied as per user
There is stop loss and take profit that can be used to optimise your trade

Extending this to,
In general guidelines for RSI :
Short-term intraday traders (day trading) often use lower settings with periods in the range of 9-11.
Medium-term swing traders frequently use the default period setting of 14.
Longer-term position traders often set it at a higher period, in the range of 20-30.

The template also includes daily square off based on your time.
