//@version=5
strategy('VS Buy Hold', precision=2)

bnh_info_panel = input(true, title='Enable Info Panel')
bnh_indicator_panel = input(true, title='Enable Indicator Panel')

//COMPARISON DATE RANGE//
bnh_start = input.time(timestamp("Jan 1 1970"), "Start Date")
bnh_finish = input.time(timestamp("Dec 31 2050"), "Start Date")
bnh_timeCond = time >= bnh_start and time <= bnh_finish ? true : false

//Note: If you are going to use the COMPARISON DATE RANGE above, apply bnh_timeCond
//      to your strategy parameters.


/////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////STRATEGY SCRIPT START//////////////////////////////////

//=========================PLACEHOLDER MA CROSS STRATEGY=========================//
fastLength = 50
slowLength = 200
price = close

mafast = ta.sma(price, fastLength)
maslow = ta.sma(price, slowLength)

positionSize = strategy.initial_capital / close

if ta.crossover(mafast, maslow) and bnh_timeCond  // <= bnh_timeCond added as a condition
    strategy.entry('MA2CrossLE', strategy.long, positionSize, comment='MA2CrossLE')

if ta.crossunder(mafast, maslow) and bnh_timeCond  // <= bnh_timeCond added as a condition
    strategy.entry('MA2CrossSE', strategy.short, positionSize, comment='MA2CrossSE')

//////////////////////////////STRATEGY SCRIPT END////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////



//STRATEGY EQUITY
strategy_pnl = strategy.netprofit + strategy.openprofit
bnh_strategy_pnl_pcnt = strategy_pnl / strategy.initial_capital * 100


//BUY AND HOLD EQUITY
float bnh_start_bar = na
bnh_start_bar := na(bnh_start_bar[1]) and bnh_timeCond ? close : bnh_start_bar[1]
bnl_buy_hold_equity = (close - bnh_start_bar) / bnh_start_bar * 100


//STRATEGY VS BUY AND HOLD STATS
bnh_vs_diff = bnh_strategy_pnl_pcnt - bnl_buy_hold_equity

bnh_bar_counter = 0
bnh_bar_counter := bnh_vs_diff > 0 ? nz(bnh_bar_counter[1]) + 1 : bnh_bar_counter[1]

bnh_bar_counter2 = 0
bnh_bar_counter2 := bnh_vs_diff <= 0 ? nz(bnh_bar_counter2[1]) + 1 : bnh_bar_counter2[1]

bnh_pcnt_above = bnh_bar_counter / (bnh_bar_counter + bnh_bar_counter2) * 100
bnh_pcnt_below = bnh_bar_counter2 / (bnh_bar_counter + bnh_bar_counter2) * 100

bnh_average_diff = ta.cum(bnh_vs_diff) / (bnh_bar_counter + bnh_bar_counter2)


//PLOTS AND LABELS
bnh_diff_color = bnh_vs_diff > 0 ? color.green : color.red
plot(bnh_vs_diff, style=plot.style_columns, color=color.new(bnh_diff_color, 60), title='SvB')
plot(bnh_strategy_pnl_pcnt, color=color.new(color.yellow, 0), linewidth=2, title='SR')
plot(bnl_buy_hold_equity, color=color.new(color.blue, 0), title='BHR')

draw_IndicatorLabel(_text, _x, _y, label_color, font_color) =>
    string_text = _text
    var label la_indicator = na
    label.delete(la_indicator)
    la_indicator := label.new(x=_x, y=_y, text=string_text, xloc=xloc.bar_index, yloc=yloc.price, color=label_color, style=label.style_label_down, textcolor=font_color, size=size.small)
    la_indicator

draw_InfoPanel(_text, _x, _y, font_size) =>
    var label la_panel = na
    label.delete(la_panel)
    la_panel := label.new(x=_x, y=_y, text=_text, xloc=xloc.bar_time, yloc=yloc.price, color=color.new(#383838, 5), style=label.style_label_up, textcolor=color.white, size=font_size)
    la_panel

if bnh_indicator_panel
    draw_IndicatorLabel('Difference', bar_index, bnh_vs_diff, color.new(color.gray, 40), color.white)
    draw_IndicatorLabel('Strategy P/L', bar_index, bnh_strategy_pnl_pcnt, color.new(color.yellow, 50), color.white)
    draw_IndicatorLabel('Buy & Hold P/L', bar_index, bnl_buy_hold_equity, color.new(color.blue, 50), color.white)

info_panel_x = time_close + math.round(ta.change(time) * 200)
info_panel_y = math.max(math.max(bnl_buy_hold_equity, bnh_strategy_pnl_pcnt), bnh_vs_diff) + math.abs(bnh_vs_diff * 0.25)


title = 'STRATEGY vs BUY & HOLD STATS'
row0 = '-----------------------------------------------------'
row1 = 'Bars Above Buy & Hold: ' + str.tostring(bnh_pcnt_above, '#.##') + '%'
row2 = 'Bars Below Buy & Hold: ' + str.tostring(bnh_pcnt_below, '#.##') + '%'
row3 = 'All Time Ave. Difference: ' + str.tostring(bnh_average_diff, '#.##') + '%'

panel_text = '\n' + title + '\n' + row0 + '\n' + row1 + '\n\n' + row2 + '\n\n' + row3 + '\n'

if bnh_info_panel
    draw_InfoPanel(panel_text, info_panel_x, info_panel_y, size.normal)

View in Pine Editor・103 lines
Use on chart
3
0
5
3
9 331
Nov 18, 2019
SUMMARY:
A strategy wrapper that makes a detailed and visual comparison between a given strategy and the buy & hold returns of the traded security.


DESCRIPTION:
TradingView has a "Buy & Hold Return" metric in the strategy tester that is often enough to assess how our strategy compares to a simple buy hold. However, one may want more information on how and when your strategy beats or is beaten by a simple buy & hold strategy. This script aims to show such detail by providing a more comprehensive metrics and charting the profit/loss of the given strategy against buy & hold.

As seen in the script, it plots/draws 4 elements:

1) Strategy P/L: strategy net profit + strategy open profit
2) Buy & Hold P/L: unrealized return
3) Difference: Strategy P/L - Buy & Hold P/L
4) Strategy vs Buy Hold Stats
> Percent of bars strategy P/L is above Buy & Hold
> Percent of bars strategy P/L is below Buy & Hold
> All Time Average Difference


ADJUSTABLE PARAMETERS:
All labels/panels can be disabled by unchecking these two options:
>bnh_info_panel = input(true, title='Enable Info Panel')
>bnh_indicator_panel = input(true, title='Enable Indicator Panel')

Comparison Date Range can be changed to better isolate specific areas:
>From Year, From Month, From Day
default: 1970 01 01

>To Year, To Month, To Day
default: 2050 12 31

Default settings basically covers all historical data.


HOW TO USE:

The default script contains a simple 50-200 SMA cross strategy, just delete and replace it. Those are everything between these lines:
/////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////STRATEGY SCRIPT START//////////////////////////////////

(STRATEGY SCRIPT GOES HERE)

//////////////////////////////STRATEGY SCRIPT END////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////

Removing all plots and drawings from your strategy is advisable.

If you are going to use the Comparison Date Range, apply "bnh_timeCond" to your strategy to align the dates. A sample on how it’s applied can be seen on the Placeholder MA cross strategy.
Note: bnh_timeCond returns a boolean series

Dec 6, 2023
Release Notes
-Updated to Pine v5.
