//@version=5
strategy("Stochastic Z-Score Oscillator Strategy [TradeDots]", shorttitle="TradeDots Stochastic Z-Score", overlay = false, max_lines_count = 500, max_boxes_count = 100, initial_capital = 10000, currency = currency.USD, commission_type = strategy.commission.percent, commission_value = 0.01, default_qty_type = strategy.percent_of_equity, default_qty_value = 30, pyramiding = 1)

// var and input
input_enable_backtest = input.bool(defval = true, title = "Enable Backtest")
input_rolling_window = input.int(defval = 80, title = "Rolling Window", minval = 1, step = 1)
input_z_thresh = input.float(defval = 2.8, title = "Z-Score Thershhold")
input_cool_down = input.int(defval = 5, title = "Signal Cool Down Period", minval = 1, step = 1)
input_stoch_length = input.int(defval = 14, title = "Stochastic Length")
input_stoch_smoothen = input.int(defval = 7, title = "Stochastic Smoothen")

var int buy_cool_down_counter = input_cool_down
var int sell_cool_down_counter = input_cool_down

// indicator results
stoch = ta.sma(ta.stoch(close, high, low, input_stoch_length),input_stoch_smoothen) / 100 * 8 - 4 //rescale to k-score 
rolling_stdev = ta.stdev(close, input_rolling_window, false)
rolling_mean = ta.sma(close, input_rolling_window)
z_score = (close - rolling_mean) / rolling_stdev

// plot & styling
z_line_opacity = z_score > 0 and z_score > z_score[1] or z_score < 0 and z_score < z_score[1] ? 20 : 60
stoch_line_opacity = stoch > 0 and stoch > stoch[1] or stoch < 0 and stoch < stoch[1] ? 20 : 40
plot(stoch, "Stochastic Line", stoch > 0 ? color.new(#5BC0BE, stoch_line_opacity) : color.new(#304C89, stoch_line_opacity), linewidth = 2)
plot(z_score, "Z-Score Line", z_score > 0 ? color.new(#9cff87, z_line_opacity) : color.new(#f9396a, z_line_opacity), linewidth = 2)
plot(input_z_thresh, "Sell Threshold", color = color.from_gradient((z_score + stoch)/2, 0, input_z_thresh, color.new(color.gray, 70), color.new(#f9396a, 0)), linewidth = 2)
plot(-input_z_thresh, "Buy Threshold", color = color.from_gradient((z_score + stoch)/2, -input_z_thresh, 0, color.new(#9cff87, 0), color.new(color.gray, 70)), linewidth = 2)
hline(0, title = "0 Level")

//strategy conditions (short)
if(z_score + stoch)/2 > input_z_thresh
    if sell_cool_down_counter >= input_cool_down
        label.new(bar_index, z_score, text = "Sell", style = label.style_label_down, color = #f9396a, textcolor = #ffffff)
        if input_enable_backtest == true 
            //strategy.close("Buy", qty_percent = 100, comment = "Close all buy orders")
            strategy.entry("Sell", strategy.short, comment = "Open Short Position")

        sell_cool_down_counter := 0
        buy_cool_down_counter := input_cool_down 

    else
        sell_cool_down_counter := sell_cool_down_counter + 1

if z_score > 0
    strategy.close("Buy", qty_percent = 100, comment = "Close all buy orders")

//strategy conditions (long)
else if (z_score + stoch)/2 < -input_z_thresh
    if buy_cool_down_counter >= input_cool_down    
        label.new(bar_index, z_score, text = "Buy", style = label.style_label_up, color = #9cff87)
        if input_enable_backtest == true    
            //strategy.close("Sell", qty_percent = 100, comment = "Close all sell orders")
            strategy.entry("Buy", strategy.long, comment = "Open Long Position")
        sell_cool_down_counter := input_cool_down
        buy_cool_down_counter := 0 
    else   
        buy_cool_down_counter := buy_cool_down_counter + 1

if z_score < 0
    strategy.close("Sell", qty_percent = 100, comment = "Close all sell orders")

View in Pine Editor・63 lines
Use on chart
5
1
8
1
11 276
The "Stochastic Z-Score Oscillator Strategy" represents an enhanced approach to the original "Buy Sell Strategy With Z-Score" trading strategy. Our upgraded Stochastic model incorporates an additional Stochastic Oscillator layer on top of the Z-Score statistical metrics, which bolsters the affirmation of potential price reversals.

We also revised our exit strategy to when the Z-Score revert to a level of zero. This amendment gives a much smaller drawdown, resulting in a better win-rate compared to the original version.

HOW DOES IT WORK

The strategy operates by calculating the Z-Score of the closing price for each candlestick. This allows us to evaluate how significantly the current price deviates from its typical volatility level.

The strategy first takes the scope of a rolling window, adjusted to the user's preference. This window is used to compute both the standard deviation and mean value. With these values, the strategic model finalizes the Z-Score. This determination is accomplished by subtracting the mean from the closing price and dividing the resulting value by the standard deviation.

Following this, the Stochastic Oscillator is utilized to affirm the Z-Score overbought and oversold indicators. This indicator operates within a 0 to 100 range, so a base adjustment to match the Z-Score scale is required. Post Stochastic Oscillator calculation, we recalibrate the figure to lie within the -4 to 4 range.

Finally, we compute the average of both the Stochastic Oscillator and Z-Score, signaling overpriced or underpriced conditions when the set threshold of positive or negative is breached.

APPLICATION

Firstly, it is better to identify a stable trading pair for this technique, such as two stocks with considerable correlation. This is to ensure conformance with the statistical model's assumption of a normal Gaussian distribution model. The ideal performance is theoretically situated within a sideways market devoid of skewness.

Following pair selection, the user should refine the span of the rolling window. A broader window smoothens the mean, more accurately capturing long-term market trends, while potentially enhancing volatility. This refinement results in fewer, yet precise trading signals.

Finally, the user must settle on an optimal Z-Score threshold, which essentially dictates the timing for buy/sell actions when the Z-Score exceeds with thresholds. A positive threshold signifies the price veering away from its mean, triggering a sell signal. Conversely, a negative threshold denotes the price falling below its mean, illustrating an underpriced condition that prompts a buy signal.

Within a normal distribution, a Z-Score of 1 records about 68% of occurrences centered at the mean, while a Z-Score of 2 captures approximately 95% of occurrences.

The 'cool down period' is essentially the number of bars that await before the next signal generation. This feature is employed to dodge the occurrence of multiple signals in a short period.

DEFAULT SETUP

The following is the default setup on EURAUD 1h timeframe
Rolling Window: 80
Z-Score Threshold: 2.8
Signal Cool Down Period: 5
Stochastic Length: 14
Stochastic Smooth Period: 7

Commission: 0.01%
Initial Capital: $10,000
Equity per Trade: 40%

FURTHER IMPLICATION

The Stochastic Oscillator imparts minimal impact on the current strategy. As such, it may be beneficial to adjust the weightings between the Z-Score and Stochastic Oscillator values or the scale of Stochastic Oscillator to test different performance outcomes.

Alternative momentum indicators such as Keltner Channels or RSI could also serve as robust confirmations of overbought and oversold signals when used for verification.

RISK DISCLAIMER

Trading entails substantial risk, and most day traders incur losses. All content, tools, scripts, articles, and education provided by TradeDots serve purely informational and educational purposes. Past performances are not definitive predictors of future results.
