//@version=5
strategy("RSI with Slow and Fast MA Crossing Strategy (by Coinrule)",
         overlay=true,
         initial_capital=10000,
         process_orders_on_close=true,
         default_qty_type=strategy.percent_of_equity,
         default_qty_value=30,
         commission_type=strategy.commission.percent,
         commission_value=0.1)

showDate = input(defval=true, title='Show Date Range')
timePeriod = time >= timestamp(syminfo.timezone, 2020, 1, 1, 0, 0)
notInTrade = strategy.position_size <= 0


// RSI
length = input(14)
vrsi = ta.rsi(close, length)

// Moving  Averages for Buy Condition
buyFastEMA = ta.ema(close, 9)
buySlowEMA = ta.ema(close, 50)
buyCondition1 = ta.crossover(buyFastEMA, buySlowEMA)


increase = 5
if ((vrsi > vrsi[1]+increase) and buyCondition1 and vrsi < 70 and timePeriod)
    strategy.entry("Long", strategy.long)


// Moving  Averages for Sell Condition
sellFastEMA = ta.ema(close, 9)
sellSlowEMA = ta.ema(close, 50)
plot(request.security(syminfo.tickerid, "60", sellFastEMA), color = color.blue)
plot(request.security(syminfo.tickerid, "60", sellSlowEMA), color = color.green)


condition = ta.crossover(sellSlowEMA, sellFastEMA)
//sellCondition1 = request.security(syminfo.tickerid, "60", condition)

strategy.close('Long', when = condition and timePeriod)

View in Pine Editor・44 lines
Use on chart
1
8
2
3
6 951
This strategy utilises 3 different conditions that have to be met to buy and 1 condition to sell. This strategy works best on the ETH/USDT pair on the 4-hour timescale.

In order for the strategy to enter the trade, it must meet all of the conditions listed below:

ENTRY
RSI increases by 5
RSI is lower than 70
MA9 crosses above MA50

To exit a trade, the below condition must be met:

EXIT
MA50 crosses above MA9

This strategy works well on LINK/USDT on the 1-day timeframe, MIOTA/USDT on the 2-hour timeframe, BTC/USDT on the 4-hour timeframe, and BEST/USDT on the 1-day timeframe (and 4h).

Back-tested from 1 January 2020.

The strategy assumes each order is using 30% of the available coins to make the results more realistic and to simulate you only ran this strategy on 30% of your holdings. A trading fee of 0.1% is also taken into account and is aligned to the base fee applied on Binance.
