//@version=5
strategy("Misery index", overlay=false)
unemployment = request.security("FRED:UNRATE","M",close) 
inflation = request.security("ECONOMICS:USIRYY","M",close)
misery = unemployment+inflation
plot(misery)
longCondition = misery<misery[1]
if (longCondition)
    strategy.entry("My Long Entry Id", strategy.long)

shortCondition = misery>misery[1]
if (shortCondition)
    strategy.entry("My Short Entry Id", strategy.short)

View in Pine Editor・15 lines
Use on chart
5
8
2 746
Hi all,

It's bear market so let's have a look at the misery index.
Misery index = inflation(%) + unemployment (%)

It's only possible to use this chart on the monthly (as misery index is updated monthly), but just for fun I added a strategy to it. If misery index increases you short and you go long when MI decreases.
Enjoy

p.s. the band is pretty cool too
