//@version=4
strategy(title="MACD SHORT STRATEGY REAL EQUITY WITH 50X LEVERAGE",shorttitle = "MACD SHORT 50X REAL EQUITY", overlay=true, 
         initial_capital=100, 
         linktoseries = false,
         default_qty_type=strategy.cash, 
         default_qty_value=1, 
         commission_type=strategy.commission.percent, 
         commission_value=0.0,
         calc_on_order_fills = false,
         calc_on_every_tick  = true,
         max_bars_back = 5000,
         pyramiding = 0,
         precision = 3)

// Variables 
src = close 

fromyear = input(2016, defval = 2009, minval = 2000, maxval = 2100, title = "From Year")
toyear = input(2100, defval = 2100, minval = 1900, maxval = 2100, title = "To Year")
frommonth = input(04, defval = 04, minval = 01, maxval = 12, title = "From Month")
tomonth = input(12, defval = 12, minval = 01, maxval = 12, title = "To Month")
fromday = input(01, defval = 01, minval = 01, maxval = 31, title = "From day")
today = input(31, defval = 31, minval = 01, maxval = 31, title = "To day")
term = (time > timestamp(fromyear, frommonth, fromday, 00, 00) and time < timestamp(toyear, tomonth, today, 23, 59))


// STRATEGY COMPONENTS
// SL values

// STOP VALUE ==> 
//The 50x leverage explodes at just 2% above the current entry price and the current position size melts.
//2% below the entry price is determined as the liquidation point so that the transaction is guaranteed.

stop_value = valuewhen(strategy.position_size != 0 and strategy.position_size[1] == 0,strategy.position_avg_price * 1.02 , 0)
//

// LEVERAGE ==> 50X

leverage = 50 

// POSITION SIZE ==> %1 (0.01)
possize = 1

// MACD

fastLength = input(12)
slowlength = input(26)
MACDLength = input(9)
MACD = ema(close, fastLength) - ema(close, slowlength)
aMACD = ema(MACD, MACDLength)
delta = MACD - aMACD

// STRATEGY

if (crossunder(delta, 0) and term)
    strategy.entry("MacdSE",strategy.short,qty = possize)
if (crossover(delta, 0) and term)
    strategy.close("MacdSE", true, comment="CLOSE")

if(high >= stop_value and delta < 0  and term )

    strategy.close("MacdSE",true)

if time > timestamp(toyear, tomonth, today, 23, 59)
    strategy.close_all()


// REAL LEVERAGE SIMULATION --- 

_longmovement = strategy.position_size != 0 and strategy.position_size[1] == 0 
_exitmovement = strategy.position_size[1] != 0 and strategy.position_size == 0

// MODE : Indicating a situation for winners and losers, just like in the martingale system, to know if the strategy is losing or gaining.

float mode = na
mode := change(strategy.wintrades) > 0 ? 1 : change(strategy.losstrades) > 0 ? -1 : nz(mode[1], 1)

float capital = 0.00
chg = change(strategy.position_size)

_b = valuewhen(_longmovement,strategy.position_avg_price,0)
_s = valuewhen(_exitmovement,open,0)

pips = ((_s - _b) / _b) * 100  
//If we are in profit, how much will this affect all of our capital with leverage?
//If we are already at a loss, all of our position size will be gone.
// Now let's put this into expression : 

                                       
capital := _longmovement ? nz(capital[1], 0) + chg : _exitmovement and mode == 1 ? (capital[1] + chg) + ((-chg * leverage * pips)/100) : 
           _exitmovement and mode != 1 ? capital[1] : capital[1]

// NET CAPITAL
capita = 100 + capital
float netcapital = na
netcapital := netcapital[1] <= 0 ? 0 : capita

// Now, if we are ready, it's time to see the facts:
//If we had made a strategy using 1% position size and 50x leverage, that is, our entry point would be less than 2% liquidation point, the change in our capital would be in the form of a blue-colored area.
//The result are still not good.
// The first moment we switch to - is the moment we run out of cash and the game is over.
// NOTE:  It is recommended to use as chart bottom indicator.

plot(netcapital , color = color.teal , linewidth = 2)

View in Pine Editor・107 lines
Use on chart
1
3
9
5 438
Dec 14, 2020

Hello there ,
Short version of the Macd Long strategy.
MACD Long strategy:




Adding margin: Forbidden or not specified. (Add Margin : No)


Position size: (for each trade) 1%



Stop-Loss: (2% Above Entry Level)



Long: macd crossunder



Exit: macd crossover




Or ofc touching the stop-Loss value as predicted.
These strategies are just examples.
The goal is to observe true equity and equity change.

Warning: This strategy simulation is for Short direction only.
Regards.

Feb 16, 2021
Release Notes
Update : Net capital bug fixed.
Mar 29, 2021
Release Notes
We forgot to add principal position size if we win. (Line 92)
The previous version was wrong.
Because this algorithm saw the starting position size as a loss. ( It was only taking into account the profit on position size.)

I also designed the percentage profit calculation much simpler.
I will do this update when I have enough time.

NOTE : My last script needs same update and its a bit complicated. It is easy but i want my codes to be simple and understandable.
Both the percentage profit command I specified and the place that is wrong and fixed in these two scripts will be fixed in the duplex macd system.
I'll update him when I have time.
My last script :



Mar 29, 2021
Release Notes
Apology!
The old version was correct.
Because change (strategy.position size) is used.
There is no need to add principal position size again.
