//@version=2
////////////////////////////////////////////////////////////
//  Copyright by HPotter v1.0 05/06/2017
// Advance-Decline Volume Percent (AD Volume Percent) is a breadth indicator 
// that measures the percentage of Net Advancing Volume for a particular group
// of stocks, such as an index or ETF. Net Advancing Volume equals the volume 
// of advances less the volume of declines. AD Volume Percent equals Net Advancing 
// Volume divided by total volume for the group. AD Volume Percent fluctuates 
// between -100% and +100%. 
//
// You can change long to short in the Input Settings
// Please, use it only for learning or paper trading. Do not for real trading
////////////////////////////////////////////////////////////
strategy(title="Advance-Decline Volume Percent Backtest", shorttitle="ADV Percent")
AdvSymbolVolume = input(title="Advancing Volume Symbol", type=symbol, defval="USI:UVOL")
DecSymbolVolume = input(title="Declining Volume Symbol", type=symbol, defval="USI:DVOL")
Resolutin = input(title="Resolution", type=resolution, defval="D")
BuyBand = input(100)
SellBand = input(-100, minval=1)
reverse = input(false, title="Trade reverse")
hline(SellBand, color=red, linestyle=line)
hline(BuyBand, color=green, linestyle=line)
xASVValue = security(AdvSymbolVolume, Resolutin, close)
xDSVValue = security(DecSymbolVolume, Resolutin, close)
xADV = xASVValue - xDSVValue
nRes = (xADV - nz(xADV[1], 0)) * 100 / (xASVValue + xDSVValue)
pos = iff(nRes > BuyBand, 1,
         iff(nRes < SellBand, -1, nz(pos[1], 0))) 
possig = iff(reverse and pos == 1, -1,
          iff(reverse and pos == -1, 1, pos))       
if (possig == 1) 
    strategy.entry("Long", strategy.long)
if (possig == -1)
    strategy.entry("Short", strategy.short)               
barcolor(possig == -1 ? red: possig == 1 ? green : blue )
plot(nRes, color=green, title="ADV Percent", style=line)

View in Pine Editor・36 lines
Use on chart
6
7
3 713
Advance-Decline Volume Percent (AD Volume Percent) is a breadth indicator
that measures the percentage of Net Advancing Volume for a particular group
of stocks, such as an index or ETF. Net Advancing Volume equals the volume
of advances less the volume of declines. AD Volume Percent equals Net Advancing
Volume divided by total volume for the group. AD Volume Percent fluctuates
between -100% and +100%.

You can change long to short in the Input Settings
Please, use it only for learning or paper trading. Do not for real trading
