//@version=5
##root(root_metainfo,rm_0,plot.style_line,cb__plot_style__integer,plot,style)
##root(root_metainfo,rm_1,plot.style_line,cb__plot_style__integer,plot,style)
##root(root_metainfo,rm_2,'shape_triangle_up',input__string,plotshape,style)
##root(root_metainfo,rm_3,'AboveBar',input__string,plotshape,location)
##root(root_metainfo,rm_4,'shape_triangle_down',input__string,plotshape,style)
##root(root_metainfo,rm_5,'BelowBar',input__string,plotshape,location)
