//@version=5
strategy("Kaufman Adaptive Moving Average (KAMA) Strategy [TradeDots]", overlay = true, max_lines_count = 500, max_boxes_count = 100, initial_capital = 10000, currency = currency.USD, commission_type = strategy.commission.percent, commission_value = 0.01, default_qty_type = strategy.percent_of_equity, default_qty_value = 80)

// KAMA Setup
lookback_period = input.int(10, title="Length", group="KAMA")
ma_source = input(close, "KAMA Soruce", group="KAMA")
fastma_length = input.int(5, "Fast MA Legnth", minval=1,group="KAMA")
slowma_length = input.int(50, "Slow MA Legnth", minval=1,group="KAMA")

// Strategy Setup
input_order_direction = input.string("Long", options = ["Long", "Short", "Long and Short"], title = "Order Direction", group = "Strategy")
kama_rising_perid = input.int(10, title="Rising Period", group="Strategy")
kama_falling_perid = input.int(10, title="Falling Period", group="Strategy")

pine_kama(source) =>
    price_change = math.abs(source - source[lookback_period])
    sum_price_change = math.sum(math.abs(source - source[1]), lookback_period)
    fastest = 2/(fastma_length + 1)
    slowest = 2/(slowma_length + 1)
    ER = price_change / sum_price_change
    SC =  math.pow((ER * (fastest-slowest) + slowest), 2)

    alpha = SC
    sum = 0.0
    sum := na(sum[1]) ? source : sum[1] + SC * (close - nz(sum[1]))

kama = pine_kama(ma_source)

if ta.rising(kama, kama_rising_perid)
    strategy.close("Short")
    if input_order_direction != "Short" and strategy.opentrades == 0
        strategy.entry("Long", strategy.long)
        label.new(bar_index, low, "🟢 Long", color = #9cff87, style = label.style_label_up)

else if ta.falling(kama, kama_falling_perid) 
    strategy.close("Long")
    if input_order_direction != "Long" and strategy.opentrades == 0
        strategy.entry("Short", strategy.short)
        label.new(bar_index, high, "🔴 Short", color = #f9396a, style = label.style_label_down, textcolor = color.white)

// Check if position is closed (Print label if true)
is_pos_closed = (strategy.position_size[1] != 0 and strategy.position_size == 0)
is_short = strategy.position_size < 0
is_long = strategy.position_size > 0

if is_pos_closed and is_short[1] 
    label.new(bar_index, low, "🟢 Close Short", color = #9cff87, style = label.style_label_up)

else if is_pos_closed and is_long[1]
    label.new(bar_index, high, "🔴 Close Long", color = #f9396a, style = label.style_label_down, textcolor = color.white)

closelinePlot = plot(close, "", display = display.none)
kamaPlot = plot(kama, title = "KAMA", color = #ffffff)
fill(kamaPlot, closelinePlot, math.max(kama,close), kama,color.new(#9cff87, 75), color.new(#9cff87, 60))
fill(kamaPlot, closelinePlot, kama, math.min(kama,close),color.new(#f9396a, 60), color.new(#f9396a, 75))

View in Pine Editor・58 lines
Use on chart
7
0
0
1
14 559
"The Kaufman Adaptive Moving Average (KAMA) Strategy" is a trend-following system that leverages the adaptive qualities of the Kaufman Adaptive Moving Average (KAMA). This strategy is distinguished by its ability to adjust dynamically to market volatility, enhancing trading accuracy by minimizing the effects of false and delayed signals often associated with the Simple Moving Average (SMA).

HOW IT WORKS

This strategy is centered around use of the Kaufman Adaptive Moving Average (KAMA) indicator, which refines the principles of the Exponential Moving Average (EMA) with a superior smoothing technique.

KAMA distinguishes itself by its responsiveness to changes in market prices through an "Efficiency Ratio (ER)." This ratio is computed by dividing the recent absolute net price change by the cumulative sum of the absolute price changes over a specified period. The resulting ER value ranges between 0 and 1, where 0 indicates high market noise and 1 reflects stronger market momentum.

Using ER, we could get the smoothing constant (SC) for the moving average derived using the following formula:


Pine Script®
fastest = 2/(fastma_length + 1)
slowest = 2/(slowma_length + 1)
SC =  math.pow((ER * (fastest-slowest) + slowest), 2)



The KAMA line is then calculated by applying the SC to the difference between the current price and the previous KAMA.

APPLICATION

For entering long positions, this strategy initializes when there is a sequence of 10 consecutive rising KAMA lines. Conversely, a sequence of 10 consecutive falling KAMA lines triggers sell orders for long positions. The same logic applies inversely for short positions.

DEFAULT SETUP

Commission: 0.01%
Initial Capital: $10,000
Equity per Trade: 80%

Users are advised to adjust and personalize this trading strategy to better match their individual trading preferences and style.

RISK DISCLAIMER

Trading entails substantial risk, and most day traders incur losses. All content, tools, scripts, articles, and education provided by TradeDots serve purely informational and educational purposes. Past performances are not definitive predictors of future results.
