//@version=3
strategy(title="Sb_Rate_Of_Change_BB_Band_strategy Version 1.0", shorttitle="ROC_BB_Strat")
source = close, length = input(9, minval=1)
roc = 100 * (source - source[length])/source[length]
//plot(roc, color=blue, title="ROC")
hline(0, title="Zero Line")


mult = input(2, minval=0.001, maxval=50)
// Draw BB on indices
//bb_s = DrawRSI ? rsi_s : DrawMFI ? mf : na
basis = sma(roc, length)
dev = mult * stdev(roc, length)
upper = basis + dev
lower = basis - dev

source1 = hlc3
length1 = input(14, minval=1), mult1 = input(2.0, minval=0.001, maxval=50)
DrawRSI_f=input(false, title="Draw RSI?", type=bool)
DrawMFI_f=input(true, title="Draw MFI?", type=bool)
HighlightBreaches=input(true, title="Highlight Oversold/Overbought?", type=bool)

DrawMFI = (not DrawMFI_f) and (not DrawRSI_f) ? true : DrawMFI_f
DrawRSI = (DrawMFI_f and DrawRSI_f) ? false : DrawRSI_f
// RSI
rsi_s = DrawRSI ? rsi(source1, length1) : na


// MFI
upper_s = DrawMFI ? sum(volume * (change(source1) <= 0 ? 0 : source1), length1) : na
lower_s = DrawMFI ? sum(volume * (change(source1) >= 0 ? 0 : source1), length1) : na
mf = DrawMFI ? rsi(upper_s, lower_s) : na


// Draw BB on indices
bb_s = DrawRSI ? rsi_s : DrawMFI ? mf : na
basis1 = sma(bb_s, length1)
dev1 = mult * stdev(bb_s, length1)
upper1 = basis1 + dev1
lower1 = basis1 - dev1


b_color = (bb_s > upper1) ? red : (bb_s < lower1) ? green : na
chk=b_color==red?-1:b_color==green?1:0
if(nz(chk[1])<0 and chk<=0)
    chk:=nz(chk[1])-1
if(nz(chk[1])>0 and chk>=0)
    chk:=nz(chk[1])+1

if(nz(chk)>10 or nz(chk)<-10)
    chk:=0

plot(chk)
g_color=chk>0?green:chk<0?red:na
bgcolor(HighlightBreaches ? g_color : na)


if (crossover(roc, lower) and chk>0)
    strategy.entry("BBandLE", strategy.long, comment="BBandLE")
else
    strategy.cancel(id="BBandLE")

if (crossunder(roc, upper) and chk<0)
    strategy.entry("BBandSE", strategy.short, comment="BBandSE")
else
    strategy.cancel(id="BBandSE")

View in Pine Editor・66 lines
Use on chart
1
0
2
1
3 064
The strategy couples the concept of rate of change along with the Bollinger bands.

Along with it LazyBear's RSI/MFI with Volatility Indicator is also taken to reduce the number of trades and improve efficiency.

Strategy (in Layman terms):

If in the past 10 candles RSI/MFI with Volatility Indicator has printed a red/green colour and the roc has gone above/below the Bollinger bands then the short/long order is placed respectively.


Message if you think of any modifications/ enhancements/ any opportunities. :)

Donations/Tips... :) -

BTC: 1BjswGcRR6c23pka7qh5t5k56j46cuyyy2
ETH: 0x64fed71c9d6c931639c7ba4671aeb6b05e6b3781
LTC: LKT2ykQ8QSzzfTDB6Tnsf12xwYPjgq95h4
