//@version=3
strategy("My Strategy", overlay=true)

longCondition = crossover(close, highest(high[1],3))
if (longCondition)
    strategy.entry("AL", strategy.long)

shortCondition = crossunder(close, lowest(low[1],3))
if (shortCondition)
    strategy.entry("SAT", strategy.short)

View in Pine Editor・10 lines
Use on chart
6
5
1
2 740
If you see "AL" you can buy, If you see "SAT" you can sell. You can use all charts, but 4 H and 1 D charts are very well..
