//@version=3
strategy(title="VIX - SHORT",overlay=true, initial_capital=25000, default_qty_value=100, default_qty_type=strategy.percent_of_equity, commission_value=5)
vixh = security("vix", "D", high)
vixl = security("vix", "D", low)
bar1 = input(21, "Enter when VIX is above", step=1)
bar2 = input(12, "Exit when VIX is below", step=1)
selyear = input(title = "Year to start trading", defval = 2010)

//plots
b1 = if(crossover(vixh, bar1))
    true
b2 = if(crossunder(vixl, bar2))
    true

//Orders
strategy.entry("Enter", long=true, when=b1 and year>=selyear)
strategy.close_all(when=b2)

View in Pine Editor・17 lines
Use on chart
8
3
3 998
This looks at he VIX and trades SVXY. Load SVXY and run the script on SVXY.

INPUTS:

Entry - You set this number to how high you want the VIX to go before SVXY will be bought. Keep in mind it buys the bar after a trigger, results may be confusing
Exit - You set this number to how low you want the VIX to go before SVXY will be sold.
Year - This as stated, It will start trading on the year you set here.

Good luck.

This script is for learning purposes, and boy did I learn something. UVXY still sucks
